/* ANSI-C code produced by gperf version 3.1 */
/* Command-line: gperf --output-file=llamafile/is_keyword_c_constant.c llamafile/is_keyword_c_constant.gperf  */
/* Computed positions: -k'1,3-6,8-9,11,13,15,20,$' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gperf@gnu.org>."
#endif

#line 1 "llamafile/is_keyword_c_constant.gperf"

#include <string.h>

#define TOTAL_KEYWORDS 769
#define MIN_WORD_LENGTH 3
#define MAX_WORD_LENGTH 36
#define MIN_HASH_VALUE 3
#define MAX_HASH_VALUE 3490
/* maximum key range = 3488, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash (register const char *str, register size_t len)
{
  static const unsigned short asso_values[] =
    {
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,   45,  815,
       480,  775,  910,  365,  330,  295,  360,   90, 3491, 3491,
      3491, 3491, 3491, 3491, 3491,   10,   45,  360,  260,   75,
        10,  140,  445,    0, 1934,    0,   40,   15,    0,   55,
         5,  445,  215,    0,    0,   95,  340,  165,   10,   65,
      1484,    0, 3491, 3491, 3491,    0,  105,    5,  550,  130,
       456,    5,  265,   10,   15,  695, 3491, 3491,  255,   15,
         0,  765,    5, 3491,    0,    5,    0,  725,   25,   20,
       405, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491, 3491,
      3491, 3491, 3491, 3491, 3491, 3491, 3491
    };
  register unsigned int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[19]];
      /*FALLTHROUGH*/
      case 19:
      case 18:
      case 17:
      case 16:
      case 15:
        hval += asso_values[(unsigned char)str[14]];
      /*FALLTHROUGH*/
      case 14:
      case 13:
        hval += asso_values[(unsigned char)str[12]];
      /*FALLTHROUGH*/
      case 12:
      case 11:
        hval += asso_values[(unsigned char)str[10]];
      /*FALLTHROUGH*/
      case 10:
      case 9:
        hval += asso_values[(unsigned char)str[8]];
      /*FALLTHROUGH*/
      case 8:
        hval += asso_values[(unsigned char)str[7]];
      /*FALLTHROUGH*/
      case 7:
      case 6:
        hval += asso_values[(unsigned char)str[5]+1];
      /*FALLTHROUGH*/
      case 5:
        hval += asso_values[(unsigned char)str[4]];
      /*FALLTHROUGH*/
      case 4:
        hval += asso_values[(unsigned char)str[3]];
      /*FALLTHROUGH*/
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      /*FALLTHROUGH*/
      case 2:
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

const char *
is_keyword_c_constant (register const char *str, register size_t len)
{
  static const char * const wordlist[] =
    {
      "", "", "",
      "NAN",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "__SSSE3__",
      "", "", "", "",
      "M_PI",
      "",
      "__INTMAX_WIDTH__",
      "", "", "",
      "INTPTR_MIN",
      "", "",
      "__TIME__",
      "", "", "", "",
      "P_tmpdir",
      "", "", "", "", "",
      "__APPLE__",
      "", "", "", "", "",
      "INTPTR_MAX",
      "", "",
      "__TIMESTAMP__",
      "", "", "", "",
      "__LINE__",
      "", "", "",
      "FLT_NORM_MAX",
      "",
      "INT_LEAST8_MIN",
      "", "", "",
      "__FILE__",
      "", "",
      "FP_FAST_FMA",
      "FP_FAST_FMAF",
      "", "", "", "",
      "INT_MAX",
      "SEM_NSEMS_MAX",
      "",
      "TZNAME_MAX",
      "FP_NAN",
      "TMP_MAX",
      "",
      "INT_LEAST8_MAX",
      "", "",
      "FLT_MAX",
      "", "", "", "",
      "PRIXMAX",
      "", "", "", "",
      "FLT_TRUE_MIN",
      "EOF",
      "__SETLB__",
      "", "",
      "FP_FAST_FMAL",
      "UINT_MIN",
      "", "", "",
      "__NO_SETLB__",
      "", "", "",
      "FP_ILOGBNAN",
      "",
      "PIPE_MAX",
      "",
      "INTMAX_MIN",
      "", "",
      "NAME_MAX",
      "", "", "", "",
      "UINT_MAX",
      "NULL",
      "", "",
      "__INT8_MAX__",
      "", "", "", "",
      "__arm__",
      "LDBL_MIN",
      "",
      "INTMAX_MAX",
      "", "", "", "", "", "",
      "__XXX__",
      "LINE_MAX",
      "",
      "__PTX_SM__",
      "BC_BASE_MAX",
      "__FMA__",
      "", "",
      "NL_LANGMAX",
      "",
      "LDBL_MIN_EXP",
      "LDBL_MAX",
      "", "", "", "",
      "OPEN_MAX",
      "", "",
      "SYMLOOP_MAX",
      "LDBL_MAX_EXP",
      "__BASE_FILE__",
      "FP_NORMAL",
      "",
      "FLT_MAX_EXP",
      "",
      "M_E",
      "", "", "",
      "__BMI__",
      "WINT_MIN",
      "", "", "", "", "", "", "",
      "UINTMAX_MIN",
      "__ABM__",
      "", "",
      "NL_TEXTMAX",
      "",
      "__SSE__",
      "LONG_MIN",
      "", "", "",
      "__PIE__",
      "WINT_MAX",
      "__XSAVE__",
      "", "",
      "__AES__",
      "",
      "FP_ILOGB0",
      "",
      "UINTMAX_MAX",
      "LDBL_EPSILON",
      "", "", "", "", "",
      "LONG_MAX",
      "NL_SETMAX",
      "__INT_LEAST8_WIDTH__",
      "", "", "", "", "", "",
      "TTY_NAME_MAX",
      "__INT_LEAST8_MAX__",
      "", "",
      "UINTPTR_MIN",
      "FLT_MANT_DIG",
      "SHRT_MIN",
      "", "", "",
      "ARG_MAX",
      "__UINT8_MAX__",
      "",
      "MB_LEN_MAX",
      "", "",
      "BC_STRING_MAX",
      "FOPEN_MAX",
      "ATEXIT_MAX",
      "",
      "__ELF__",
      "__UINT_FAST8_MAX__",
      "", "",
      "UINTPTR_MAX",
      "",
      "SHRT_MAX",
      "WEOF",
      "__NO_LIW__",
      "", "", "", "",
      "__UINTMAX_MAX__",
      "",
      "__ppc__",
      "", "", "",
      "_IONBF",
      "", "", "", "", "",
      "__SGX__",
      "", "", "",
      "_IOFBF",
      "", "",
      "UINT_FAST8_MAX",
      "LDBL_MIN_10_EXP",
      "", "", "",
      "SIG_ATOMIC_MIN",
      "", "",
      "FILENAME_MAX",
      "", "",
      "LDBL_MAX_10_EXP",
      "", "", "",
      "NSIG",
      "", "",
      "__WINT_MIN__",
      "__DATE__",
      "", "", "", "", "",
      "SIG_ATOMIC_MAX",
      "",
      "_IOLBF",
      "__WINT_MAX__",
      "",
      "FLT_RADIX",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "FP_INFINITE",
      "", "", "", "", "",
      "__LIW__",
      "__SIG_ATOMIC_MIN__",
      "",
      "__SIG_ATOMIC_WIDTH__",
      "", "", "", "", "", "", "",
      "__SIG_ATOMIC_MAX__",
      "", "", "", "",
      "__INT64_MAX__",
      "",
      "__POPCNT__",
      "",
      "PRIXPTR",
      "", "", "", "", "", "",
      "LOGIN_NAME_MAX",
      "", "", "", "",
      "LLONG_MIN",
      "BC_DIM_MAX",
      "",
      "DBL_NORM_MAX",
      "", "",
      "__PTRDIFF_MAX__",
      "", "", "", "", "", "", "",
      "LONG_LONG_MIN",
      "",
      "__VA_OPT__",
      "", "",
      "INT8_MIN",
      "", "", "", "",
      "__ARM_FP_FAST",
      "", "", "",
      "DBL_MAX",
      "",
      "LLONG_MAX",
      "", "", "",
      "LONG_LONG_MAX",
      "", "", "",
      "DBL_TRUE_MIN",
      "INT8_MAX",
      "",
      "__RX_ALLOW_STRING_INSNS__",
      "",
      "__ADX__",
      "__MACH__",
      "", "", "", "",
      "EXPR_NEST_MAX",
      "INT_FAST64_MIN",
      "", "", "", "",
      "ULONG_MIN",
      "NZERO",
      "", "",
      "__FMA4__",
      "",
      "INT_LEAST16_MIN",
      "", "", "", "", "", "", "",
      "LDBL_TRUE_MIN",
      "INT_FAST64_MAX",
      "", "", "", "", "", "", "", "", "",
      "",
      "INT_LEAST16_MAX",
      "",
      "__FUNCTION__",
      "__VAES__",
      "ULONG_MAX",
      "PRIXLEAST8",
      "", "", "",
      "__WINT_WIDTH__",
      "",
      "__FNO_OMIT_FRAME_POINTER__",
      "",
      "INT_FAST8_MIN",
      "__EMSCRIPTEN__",
      "__UINTPTR_MAX__",
      "__MFENTRY__",
      "", "",
      "__SSE4A__",
      "", "", "", "", "",
      "__PCLMUL__",
      "DBL_MAX_EXP",
      "",
      "LDBL_NORM_MAX",
      "", "", "",
      "__VSX__",
      "INT_FAST8_MAX",
      "ULONG_LONG_MIN",
      "__INT_FAST64_WIDTH__",
      "LDBL_HAS_SUBNORM",
      "", "", "",
      "PRIBLEAST8",
      "",
      "__AVX__",
      "__INT_FAST64_MAX__",
      "", "", "",
      "__PIC__",
      "PATH_MAX",
      "", "", "",
      "SCNxMAX",
      "",
      "ULONG_LONG_MAX",
      "__ARM_NEON",
      "UINT_LEAST64_MAX",
      "PRIxMAX",
      "LDBL_DIG",
      "", "", "", "", "", "", "", "", "",
      "",
      "NL_MSGMAX",
      "FLT_ROUNDS",
      "__COSMOPOLITAN__",
      "",
      "__GNUC__",
      "__HAIKU__",
      "", "", "",
      "_COSMO_SOURCE",
      "", "", "",
      "DBL_MANT_DIG",
      "", "",
      "MB_CUR_MAX",
      "",
      "__INT_FAST8_MAX__",
      "__INT16_MAX__",
      "", "",
      "__NEXT_RUNTIME__",
      "", "", "", "", "",
      "__TM_FENCE__",
      "__STDC__",
      "",
      "UINT_LEAST8_MAX",
      "",
      "HLF_MAX",
      "SCNdMAX",
      "",
      "M_PIl",
      "__AVXVNNI__",
      "",
      "PRIdMAX",
      "",
      "false",
      "__ANDROID__",
      "",
      "__llvm__",
      "__UINT16_MAX__",
      "",
      "__VA_ARGS__",
      "__CET__",
      "LONG_BIT",
      "__GLIBC__",
      "",
      "__FreeBSD__",
      "", "",
      "__INT_LEAST16_MAX__",
      "M_PIf",
      "",
      "BC_SCALE_MAX",
      "__FLT16_MIN__",
      "",
      "INT_LEAST32_MIN",
      "",
      "__HIP__",
      "__FLT16_MANT_DIG__",
      "", "",
      "_GNU_SOURCE",
      "__SHA__",
      "__FLT16_MAX__",
      "UINT8_MIN",
      "", "", "", "",
      "__UINT_FAST16_MAX__",
      "", "", "", "",
      "__GNUC_MINOR__",
      "INT_LEAST32_MAX",
      "FLT_EPSILON",
      "", "", "",
      "__CYGWIN__",
      "", "", "", "", "", "", "",
      "CHAR_MIN",
      "DELAYTIMER_MAX",
      "", "", "",
      "__FAST_MATH__",
      "UINT8_MAX",
      "",
      "FLT_IS_IEC_60559",
      "", "",
      "M_El",
      "", "", "", "", "", "",
      "__POWERPC__",
      "",
      "CHAR_MAX",
      "",
      "UINT_FAST16_MAX",
      "", "",
      "SEM_VALUE_MAX",
      "", "", "", "",
      "_XOPEN_SOURCE",
      "M_Ef",
      "__MSVCRT__",
      "COLL_WEIGHTS_MAX",
      "CLK_TCK",
      "__ARM_FEATURE_NUMERIC_MAXMIN",
      "__ARM_FEATURE_FRINT",
      "", "",
      "__POWER9_VECTOR__",
      "", "",
      "__NetBSD__",
      "",
      "__ARM_FEATURE_FMA",
      "HOST_NAME_MAX",
      "", "", "",
      "__FLT16_MIN_EXP__",
      "", "",
      "FLT_HAS_SUBNORM",
      "PTRDIFF_MIN",
      "M_PI_4l",
      "", "", "", "",
      "__FLT16_MAX_EXP__",
      "",
      "__GNUC_GNU_INLINE__",
      "__UINT_LEAST64_MAX__",
      "",
      "M_PI_4f",
      "",
      "__STDC_NO_ATOMICS__",
      "ULLONG_MIN",
      "__BIGGEST_ALIGNMENT__",
      "__FLT16_EPSILON__",
      "", "", "",
      "PTRDIFF_MAX",
      "", "",
      "__FATCOSMOCC__",
      "", "", "", "", "", "",
      "__INTPTR_WIDTH__",
      "",
      "LDBL_MANT_DIG",
      "",
      "ULLONG_MAX",
      "",
      "__ARM_FEATURE_FP16_FML",
      "__RX_DISALLOW_STRING_INSNS__",
      "__INTPTR_MAX__",
      "", "", "",
      "__GNUG__",
      "", "",
      "__INTEL_COMPILER",
      "", "",
      "__UINT32_MAX__",
      "",
      "__cplusplus",
      "", "",
      "__UINT_LEAST8_MAX__",
      "__CRTDLL__",
      "", "", "",
      "__INT_LEAST32_MAX__",
      "",
      "__INT_LEAST16_WIDTH__",
      "", "",
      "NL_ARGMAX",
      "__PTX_ISA_VERSION_MINOR__",
      "", "", "", "", "", "",
      "__FLT16_IS_IEC_60559__",
      "",
      "__LONG_WIDTH__",
      "__PTX_ISA_VERSION_MAJOR__",
      "", "",
      "__mips__",
      "__UINT_FAST32_MAX__",
      "M_2_SQRTPI",
      "LDBL_DECIMAL_DIG",
      "SCNxPTR",
      "", "", "",
      "_BSD_SOURCE",
      "PRIxPTR",
      "", "", "",
      "PRIXLEAST16",
      "", "",
      "true",
      "PRIX8",
      "", "", "", "", "", "", "", "", "",
      "MATH_ERRNO",
      "", "", "",
      "__RDRND__",
      "__RDSEED__",
      "", "", "",
      "__STDC_MB_MIGHT_NEQ_WC__",
      "", "", "",
      "__MSVCRT_VERSION__",
      "",
      "UINT_FAST32_MAX",
      "", "", "", "", "",
      "PRIBLEAST16",
      "SCNiMAX",
      "__FLT16_NORM_MAX__",
      "",
      "PRIB8",
      "",
      "PRIiMAX",
      "SCNdPTR",
      "",
      "__amd64__",
      "", "",
      "PRIdPTR",
      "SCHAR_MIN",
      "",
      "__SUPPORT_SNAN__",
      "", "", "", "", "", "", "", "", "",
      "",
      "FP_SUBNORMAL",
      "",
      "PRIXFAST8",
      "", "",
      "SCNuMAX",
      "",
      "CHILD_MAX",
      "",
      "NDEBUG",
      "PRIuMAX",
      "", "", "",
      "M_LN2l",
      "", "",
      "SCHAR_MAX",
      "UINT64_MIN",
      "M_LN2f",
      "", "",
      "__STDC_NO_THREADS__",
      "", "", "",
      "__INT_WIDTH__",
      "",
      "SCNxLEAST8",
      "", "", "", "",
      "PRIxLEAST8",
      "", "", "",
      "PRIBFAST8",
      "UINT64_MAX",
      "", "", "", "", "", "",
      "SCNoMAX",
      "__BMI2__",
      "INT_FAST32_MIN",
      "", "",
      "PRIoMAX",
      "",
      "__BUILTIN_CPU_SUPPORTS__",
      "__HIP_PLATFORM_AMD__",
      "", "", "", "", "",
      "__INT_LEAST32_WIDTH__",
      "",
      "__SSE2__",
      "",
      "__SET_FPSCR_RN_RETURNS_FPSCR__",
      "",
      "__NO_MATH_ERRNO__",
      "L_tmpnam",
      "INT_FAST32_MAX",
      "",
      "__COUNTER__",
      "", "",
      "USHRT_MIN",
      "",
      "DBL_EPSILON",
      "__CHAR_BIT__",
      "", "",
      "__STDC_DEC_FP__",
      "SCNdLEAST8",
      "", "",
      "UCHAR_MIN",
      "",
      "PRIdLEAST8",
      "", "",
      "INT_FAST16_MIN",
      "", "",
      "__VEC__",
      "M_LOG10E",
      "__CLFLUSHOPT__",
      "FLT_DECIMAL_DIG",
      "DBL_IS_IEC_60559",
      "__ROUNDING_MATH__",
      "",
      "HUGE_VALF",
      "", "", "", "",
      "USHRT_MAX",
      "__AVXVNNIINT8__",
      "", "", "",
      "INT_FAST16_MAX",
      "", "", "", "",
      "UCHAR_MAX",
      "__INT_FAST32_WIDTH__",
      "", "",
      "HUGE_VAL",
      "FLT_MAX_10_EXP",
      "__GNUC_STDC_INLINE__",
      "",
      "PRIXLEAST128",
      "__INT_FAST32_MAX__",
      "__INT_FAST8_WIDTH__",
      "", "", "", "", "", "", "", "", "",
      "__PRETTY_FUNCTION__",
      "__SSE4_2__",
      "UINT_LEAST32_MAX",
      "", "",
      "__SHRT_WIDTH__",
      "DBL_HAS_SUBNORM",
      "", "", "", "",
      "__STDC_NO_VLA__",
      "", "",
      "__FLT16_DIG__",
      "", "", "", "",
      "__INT32_MAX__",
      "WCHAR_MIN",
      "__INT_FAST16_WIDTH__",
      "",
      "PRIBLEAST128",
      "CHAR_BIT",
      "HUGE_VALL",
      "", "", "",
      "__INT_FAST16_MAX__",
      "",
      "__STDC_UTF_16__",
      "", "",
      "_MSC_VER",
      "", "", "", "",
      "__m68k__",
      "",
      "SCNbLEAST8",
      "UINT_LEAST16_MAX",
      "__ARM_FEATURE_RNG",
      "", "",
      "PRIbLEAST8",
      "__STDC_IEC_559__",
      "", "",
      "WCHAR_MAX",
      "", "", "", "",
      "__linux__",
      "", "", "", "", "",
      "INT_LEAST64_MIN",
      "__ARM_FEATURE_ATOMICS",
      "",
      "__SSE3__",
      "", "", "", "", "", "",
      "__MNOP_MCOUNT__",
      "", "",
      "CHARCLASS_NAME_MAX",
      "", "",
      "__STDC_VERSION__",
      "",
      "WORD_BIT",
      "__STDC_NO_COMPLEX__",
      "INT_LEAST64_MAX",
      "", "", "", "", "", "",
      "SCNiPTR",
      "", "",
      "M_LN2",
      "",
      "PRIiPTR",
      "",
      "__STDC_IEC_559_COMPLEX__",
      "__FLT16_DENORM_MIN__",
      "", "", "", "", "", "", "", "", "",
      "",
      "PRIXLEAST32",
      "", "", "",
      "__ARM_FEATURE_MATMUL_INT8",
      "", "",
      "__WCHAR_MIN__",
      "__FLT_EVAL_METHOD__",
      "", "",
      "SCNuPTR",
      "", "", "", "",
      "PRIuPTR",
      "__WCHAR_MAX__",
      "", "", "",
      "M_PI_2l",
      "", "",
      "RE_DUP_MAX",
      "", "",
      "__ARM_FEATURE_QBIT",
      "", "", "",
      "M_PI_2f",
      "", "", "",
      "PRIBLEAST32",
      "__FLT16_HAS_INFINITY__",
      "",
      "__ARM_FEATURE_QRDMX",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "SCNoPTR",
      "", "",
      "__ARM_FEATURE_CRYPTO",
      "",
      "PRIoPTR",
      "", "", "", "", "",
      "__ARM_FEATURE_SHA2",
      "",
      "__UINT_LEAST32_MAX__",
      "__OpenBSD__",
      "", "", "", "", "",
      "M_LOG2E",
      "", "",
      "__STDC_UTF_32__",
      "", "", "", "",
      "SCNiLEAST8",
      "", "", "",
      "__GCC_ASM_FLAG_OUTPUTS__",
      "PRIiLEAST8",
      "", "", "",
      "__UINT64_MAX__",
      "",
      "SCNxLEAST16",
      "",
      "__MRECORD_MCOUNT__",
      "__VPCLMULQDQ__",
      "SCNx8",
      "PRIxLEAST16",
      "", "",
      "__INT_LEAST64_MAX__",
      "PRIx8",
      "", "", "",
      "MATH_ERREXCEPT",
      "__UINT_LEAST16_MAX__",
      "", "",
      "__AVX2__",
      "",
      "SCNuLEAST8",
      "__COSMOCC__",
      "__INCLUDE_LEVEL__",
      "", "",
      "PRIuLEAST8",
      "", "", "",
      "__UINT_FAST64_MAX__",
      "", "", "", "", "", "", "", "", "",
      "__clang__",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "SCNdLEAST16",
      "", "",
      "DBL_DECIMAL_DIG",
      "SCNd8",
      "PRIdLEAST16",
      "", "",
      "SCNoLEAST8",
      "PRId8",
      "",
      "__riscv",
      "SCNxFAST8",
      "PRIoLEAST8",
      "__AVX512F__",
      "", "",
      "PRIxFAST8",
      "UINT_FAST64_MAX",
      "__ARM_FEATURE_DOTPROD",
      "", "",
      "__AVX512IFMA__",
      "",
      "__powerpc__",
      "__PTRDIFF_WIDTH__",
      "",
      "DBL_MAX_10_EXP",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "__LONG_LONG_WIDTH__",
      "", "", "", "", "",
      "PRIXFAST16",
      "__FLT16_DECIMAL_DIG__",
      "__AVX512BW__",
      "", "",
      "UINT16_MIN",
      "DECIMAL_DIG",
      "", "", "", "",
      "M_2_SQRTPIl",
      "", "", "",
      "SCNdFAST8",
      "__chibicc__",
      "", "", "",
      "PRIdFAST8",
      "", "", "", "",
      "UINT16_MAX",
      "", "", "", "",
      "__FLT16_HAS_DENORM__",
      "M_2_SQRTPIf",
      "M_SQRT2",
      "",
      "INT16_MIN",
      "PRIBFAST16",
      "", "", "", "",
      "__SSE4_1__",
      "", "", "",
      "__GNUC_PATCHLEVEL__",
      "",
      "SCNbLEAST16",
      "", "", "",
      "SCNb8",
      "PRIbLEAST16",
      "", "", "",
      "PRIb8",
      "M_PI_2",
      "", "", "", "",
      "__INT_LEAST64_WIDTH__",
      "",
      "M_SQRT2l",
      "INT16_MAX",
      "", "", "", "", "",
      "__STDC_HOSTED__",
      "", "", "", "", "",
      "M_PI_4",
      "", "", "", "", "",
      "SCNxLEAST128",
      "M_SQRT2f",
      "", "", "",
      "PRIxLEAST128",
      "", "", "", "", "", "", "",
      "PRIXFAST64",
      "", "", "",
      "M_LOG10El",
      "", "", "", "", "", "", "", "", "",
      "SCNbFAST8",
      "PRIXFAST32",
      "", "", "",
      "PRIbFAST8",
      "", "", "",
      "__WCHAR_UNSIGNED__",
      "M_LOG10Ef",
      "",
      "__ARM_FEATURE_FP16_VECTOR_ARITHMETIC",
      "", "", "", "", "", "", "",
      "INT64_MIN",
      "PRIBFAST64",
      "__AVXVNNIINT16__",
      "",
      "SCNdLEAST128",
      "", "", "", "",
      "PRIdLEAST128",
      "", "", "", "", "",
      "INT32_MIN",
      "PRIBFAST32",
      "", "", "", "",
      "__ARM_ARCH",
      "", "", "",
      "__ARM_FP16_FORMAT_ALTERNATIVE",
      "__FLT16_MIN_10_EXP__",
      "", "", "",
      "INT64_MAX",
      "", "", "", "", "",
      "__FLT16_MAX_10_EXP__",
      "",
      "__ARM_FEATURE_SM3",
      "__ARM_FEATURE_SHA3",
      "",
      "__ARM_FP16_ARGS",
      "", "", "",
      "INT32_MAX",
      "", "",
      "__STDC_LIB_EXT1__",
      "", "",
      "__ARM_FP16_IEEE",
      "", "", "", "",
      "INT128_MIN",
      "", "", "", "", "",
      "SCNiLEAST16",
      "",
      "__NetBSD_Version__",
      "",
      "SCNi8",
      "PRIiLEAST16",
      "",
      "__F16C__",
      "",
      "PRIi8",
      "SCNxLEAST32",
      "", "", "",
      "INT128_MAX",
      "PRIxLEAST32",
      "", "", "", "", "", "",
      "__riscv_flen",
      "", "", "",
      "__AVX512DQ__",
      "__CUDA_ARCH__",
      "", "",
      "SCNuLEAST16",
      "", "", "",
      "SCNu8",
      "PRIuLEAST16",
      "SCNbLEAST128",
      "__FLT16_HAS_QUIET_NAN__",
      "__func__",
      "PRIu8",
      "",
      "PRIbLEAST128",
      "",
      "__ARM_FEATURE_CRC32",
      "",
      "PRIX16",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "SCNdLEAST32",
      "",
      "SCNiFAST8",
      "", "",
      "PRIdLEAST32",
      "",
      "PRIiFAST8",
      "",
      "SCNoLEAST16",
      "",
      "__CUDA_ARCH_LIST__",
      "",
      "SCNo8",
      "PRIoLEAST16",
      "",
      "__STDC_ISO_10646__",
      "",
      "PRIo8",
      "PRIB16",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "SCNuFAST8",
      "", "", "", "",
      "PRIuFAST8",
      "M_SQRT1_2l",
      "", "",
      "__SIZEOF_INT__",
      "", "",
      "__SIZEOF_WINT_T__",
      "__AVX512VL__",
      "",
      "__AVX512VNNI__",
      "M_SQRT1_2f",
      "",
      "__ARM_FEATURE_SM4",
      "", "", "",
      "__SIZE_MAX__",
      "__SIZEOF_UINTMAX__",
      "", "", "",
      "_ARCH_PWR5X",
      "", "",
      "__AVX512VBMI__",
      "", "",
      "__AVX512CD__",
      "M_LOG2El",
      "",
      "BUFSIZ",
      "__SIZEOF_INTMAX__",
      "", "",
      "SCNoFAST8",
      "", "", "", "",
      "PRIoFAST8",
      "", "", "", "", "", "", "", "",
      "M_LOG2Ef",
      "", "", "",
      "SIZE_MIN",
      "", "",
      "__SIZEOF_FLOAT__",
      "SCNbLEAST32",
      "", "", "", "",
      "PRIbLEAST32",
      "",
      "__riscv_xlen",
      "",
      "__ARM_FEATURE_SHA512",
      "", "", "", "", "", "",
      "SIZE_MAX",
      "", "", "", "", "", "", "", "",
      "__SIZEOF_SIZE_T__",
      "SCNiLEAST128",
      "", "", "", "",
      "PRIiLEAST128",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "SCNxFAST16",
      "PRIXFAST128",
      "__STDC_WANT_LIB_EXT1__",
      "", "",
      "PRIxFAST16",
      "", "", "", "", "",
      "PRIX64",
      "SCNuLEAST128",
      "", "", "",
      "FP_ZERO",
      "PRIuLEAST128",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "PRIBFAST128",
      "__SIZEOF_POINTER__",
      "", "", "", "", "", "", "", "",
      "PRIB64",
      "", "", "", "",
      "SCNdFAST16",
      "SCNoLEAST128",
      "", "",
      "UINT32_MIN",
      "PRIdFAST16",
      "PRIoLEAST128",
      "__SIZE_WIDTH__",
      "", "", "", "", "", "", "", "",
      "__wasm_simd128__",
      "", "", "", "", "",
      "__i686__",
      "",
      "UINT32_MAX",
      "", "",
      "__s390__",
      "__s390x__",
      "",
      "__SIZEOF_DOUBLE__",
      "", "", "", "", "", "",
      "SSIZE_MAX",
      "", "", "", "", "", "",
      "SCNxFAST64",
      "UINT128_MIN",
      "", "",
      "__SIZEOF_LONG__",
      "PRIxFAST64",
      "SCNiLEAST32",
      "__aarch64__",
      "", "", "",
      "PRIiLEAST32",
      "",
      "__i586__",
      "",
      "SCNxFAST32",
      "__MINGW32__",
      "", "", "",
      "PRIxFAST32",
      "UINT128_MAX",
      "", "", "",
      "__SCHAR_WIDTH__",
      "M_LN10",
      "", "",
      "M_SQRT1_2",
      "", "", "", "", "", "",
      "SCNuLEAST32",
      "", "", "", "",
      "PRIuLEAST32",
      "", "", "", "", "", "", "",
      "__SIZEOF_LONG_LONG__",
      "SCNbFAST16",
      "SCNdFAST64",
      "", "", "",
      "PRIbFAST16",
      "PRIdFAST64",
      "", "", "", "", "", "", "", "", "",
      "SCNdFAST32",
      "", "", "", "",
      "PRIdFAST32",
      "", "", "", "",
      "SCNoLEAST32",
      "", "", "", "",
      "PRIoLEAST32",
      "",
      "__AARCH64EB__",
      "__SIZEOF_PTRDIFF_T__",
      "",
      "L_ctermid",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "__ia16__",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "SCNx16",
      "", "", "",
      "SCNbFAST64",
      "PRIx16",
      "", "", "",
      "PRIbFAST64",
      "", "", "", "", "", "", "", "", "",
      "SCNbFAST32",
      "", "", "", "",
      "PRIbFAST32",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "__MNO_VZEROUPPER__",
      "", "", "", "",
      "__SIZEOF_WCHAR_T__",
      "", "", "",
      "PRIXLEAST64",
      "", "", "",
      "__WCHAR_WIDTH__",
      "",
      "SCNd16",
      "", "",
      "SCNiFAST16",
      "",
      "PRId16",
      "", "",
      "PRIiFAST16",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "PRIBLEAST64",
      "", "", "",
      "SCNuFAST16",
      "", "", "", "",
      "PRIuFAST16",
      "", "", "", "", "", "",
      "M_LN10l",
      "", "", "", "", "",
      "__gun_linux__",
      "", "",
      "INT_MIN",
      "M_LN10f",
      "__MICROBLAZE__",
      "__CLZERO__",
      "", "", "", "", "", "",
      "FLT_MIN",
      "", "", "", "", "",
      "PRIX128",
      "", "",
      "SCNoFAST16",
      "", "", "", "",
      "PRIoFAST16",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "SCNb16",
      "", "", "",
      "SCNiFAST64",
      "PRIb16",
      "", "", "",
      "PRIiFAST64",
      "SCNxFAST128",
      "PRIB128",
      "",
      "__AVX512FP16__",
      "__MNO_RED_ZONE__",
      "PRIxFAST128",
      "", "", "",
      "SCNiFAST32",
      "SCNx64",
      "", "", "",
      "PRIiFAST32",
      "PRIx64",
      "", "", "", "", "", "", "", "",
      "SCNuFAST64",
      "", "", "", "",
      "PRIuFAST64",
      "_WIN32",
      "", "", "", "", "", "", "",
      "__AVX512BF16__",
      "SCNuFAST32",
      "", "", "", "",
      "PRIuFAST32",
      "PRIX32",
      "", "", "",
      "FLT_MIN_EXP",
      "__SIZEOF_LONG_DOUBLE__",
      "SCNdFAST128",
      "", "", "", "",
      "PRIdFAST128",
      "", "", "", "",
      "SCNd64",
      "", "",
      "SCNoFAST64",
      "",
      "PRId64",
      "", "",
      "PRIoFAST64",
      "", "", "", "", "", "",
      "INFINITY",
      "", "",
      "SCNoFAST32",
      "PRIB32",
      "", "", "",
      "PRIoFAST32",
      "", "", "", "", "",
      "__AVX5124VNNIW__",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "__powerpc64__",
      "", "", "", "",
      "__STDC_ANALYZABLE__",
      "",
      "__x86_64__",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "__i386__",
      "", "", "", "", "", "", "",
      "SCNi16",
      "", "",
      "__MWAITX__",
      "",
      "PRIi16",
      "", "", "", "",
      "SCNbFAST128",
      "", "", "", "",
      "PRIbFAST128",
      "", "", "", "",
      "SCNb64",
      "", "",
      "__STRICT_ANSI__",
      "",
      "PRIb64",
      "", "", "", "",
      "SCNu16",
      "", "", "", "",
      "PRIu16",
      "", "", "",
      "__SIZEOF_SHORT__",
      "", "", "", "", "", "", "", "", "",
      "",
      "FILESIZEBITS",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "SCNo16",
      "", "", "",
      "MQ_PRIO_MAX",
      "PRIo16",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "DBL_MIN",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "__i486__",
      "", "",
      "__Fuchsia__",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "SCNxLEAST64",
      "", "", "", "",
      "PRIxLEAST64",
      "", "", "", "",
      "SCNiFAST128",
      "", "", "", "",
      "PRIiFAST128",
      "", "", "", "",
      "SCNi64",
      "", "", "", "",
      "PRIi64",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "SCNuFAST128",
      "", "", "", "",
      "PRIuFAST128",
      "", "", "", "",
      "SCNu64",
      "SCNdLEAST64",
      "", "", "",
      "PRIu64",
      "PRIdLEAST64",
      "", "",
      "DBL_MIN_EXP",
      "", "", "", "", "",
      "FLT_DIG",
      "", "", "", "", "", "", "", "", "",
      "",
      "SCNx128",
      "", "", "",
      "SCNoFAST128",
      "PRIx128",
      "", "", "",
      "PRIoFAST128",
      "", "", "", "",
      "SCNo64",
      "", "", "", "",
      "PRIo64",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "HLF_MIN",
      "",
      "SCNd128",
      "", "", "", "",
      "PRId128",
      "", "", "", "",
      "__RDPID__",
      "", "", "", "", "", "", "",
      "SCNbLEAST64",
      "", "", "", "",
      "PRIbLEAST64",
      "", "", "",
      "M_2_PI",
      "SCNx32",
      "", "", "", "",
      "PRIx32",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "__ARM_FEATURE_CLZ",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "SCNd32",
      "", "", "", "",
      "PRId32",
      "", "", "", "", "", "", "", "", "",
      "SCNb128",
      "", "", "", "",
      "PRIb128",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "__mips64",
      "", "", "", "", "",
      "__FINITE_MATH_ONLY__",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "SCNiLEAST64",
      "", "", "", "",
      "PRIiLEAST64",
      "", "", "", "",
      "SCNb32",
      "", "", "", "",
      "PRIb32",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "SCNuLEAST64",
      "", "", "", "",
      "PRIuLEAST64",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "DBL_DIG",
      "", "", "", "",
      "SCNoLEAST64",
      "", "", "", "",
      "PRIoLEAST64",
      "SCNi128",
      "", "", "", "",
      "PRIi128",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "SCNu128",
      "", "", "", "",
      "PRIu128",
      "", "", "", "", "", "", "", "",
      "M_2_PIl",
      "", "", "", "", "", "", "", "", "",
      "M_2_PIf",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "SCNo128",
      "", "", "", "",
      "PRIo128",
      "", "", "",
      "SCNi32",
      "", "", "", "",
      "PRIi32",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "SCNu32",
      "", "", "", "",
      "PRIu32",
      "", "", "", "", "", "", "", "",
      "M_1_PI",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "SCNo32",
      "",
      "FLT_MIN_10_EXP",
      "", "",
      "PRIo32",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "M_1_PIl",
      "", "", "", "", "", "", "", "", "",
      "M_1_PIf",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "DBL_MIN_10_EXP",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "LDBL_IS_IEC_60559",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "__OPTIMIZE__"
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register unsigned int key = hash (str, len);

      if (key <= MAX_HASH_VALUE)
        {
          register const char *s = wordlist[key];

          if (*str == *s && !strncmp (str + 1, s + 1, len - 1) && s[len] == '\0')
            return s;
        }
    }
  return 0;
}
