/* ANSI-C code produced by gperf version 3.1 */
/* Command-line: gperf llamafile/is_keyword_swift_type.gperf  */
/* Computed positions: -k'1,3-6,8-9,11,13,15,17,20,22-23,26,33' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gperf@gnu.org>."
#endif

#line 1 "llamafile/is_keyword_swift_type.gperf"

#include <string.h>

#define TOTAL_KEYWORDS 1341
#define MIN_WORD_LENGTH 3
#define MAX_WORD_LENGTH 63
#define MIN_HASH_VALUE 34
#define MAX_HASH_VALUE 11694
/* maximum key range = 11661, duplicates = 0 */

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash (register const char *str, register size_t len)
{
  static const unsigned short asso_values[] =
    {
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,     0,     5,
         55,    15,   175,     0,    75,     0,   215, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695,  1785,  1050,    30,  1140,   555,
       1200,  1910,   385,   140,    45,  1495,   635,    25,    10,  1927,
        325,   685,   380,   195,  1610,    10,  1054,   530,    25, 11695,
          5, 11695, 11695, 11695, 11695,    10, 11695,     5,  2022,   185,
         30,     0,  1901,   130,  1585,    15,     5,  1895,    20,   390,
         10,     5,   240,   825,     5,     0,    10,    15,  1825,  1165,
       1459,  1045,   595, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695, 11695,
      11695, 11695, 11695, 11695, 11695, 11695
    };
  register unsigned int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[32]];
      /*FALLTHROUGH*/
      case 32:
      case 31:
      case 30:
      case 29:
      case 28:
      case 27:
      case 26:
        hval += asso_values[(unsigned char)str[25]];
      /*FALLTHROUGH*/
      case 25:
      case 24:
      case 23:
        hval += asso_values[(unsigned char)str[22]];
      /*FALLTHROUGH*/
      case 22:
        hval += asso_values[(unsigned char)str[21]];
      /*FALLTHROUGH*/
      case 21:
      case 20:
        hval += asso_values[(unsigned char)str[19]];
      /*FALLTHROUGH*/
      case 19:
      case 18:
      case 17:
        hval += asso_values[(unsigned char)str[16]];
      /*FALLTHROUGH*/
      case 16:
      case 15:
        hval += asso_values[(unsigned char)str[14]];
      /*FALLTHROUGH*/
      case 14:
      case 13:
        hval += asso_values[(unsigned char)str[12]];
      /*FALLTHROUGH*/
      case 12:
      case 11:
        hval += asso_values[(unsigned char)str[10]];
      /*FALLTHROUGH*/
      case 10:
      case 9:
        hval += asso_values[(unsigned char)str[8]];
      /*FALLTHROUGH*/
      case 8:
        hval += asso_values[(unsigned char)str[7]];
      /*FALLTHROUGH*/
      case 7:
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      /*FALLTHROUGH*/
      case 5:
        hval += asso_values[(unsigned char)str[4]];
      /*FALLTHROUGH*/
      case 4:
        hval += asso_values[(unsigned char)str[3]];
      /*FALLTHROUGH*/
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      /*FALLTHROUGH*/
      case 2:
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

const char *
is_keyword_swift_type (register const char *str, register size_t len)
{
  static const char * const wordlist[] =
    {
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "UInt",
      "", "", "", "",
      "Unit",
      "Units",
      "", "", "", "", "", "", "", "", "",
      "",
      "Mirror",
      "", "",
      "CInt",
      "", "", "", "",
      "Mode",
      "", "", "", "",
      "Code",
      "CBool",
      "", "",
      "NSMeasurement",
      "",
      "MirrorPath",
      "", "",
      "UnitMass",
      "", "",
      "CFloat",
      "", "", "", "",
      "NSNull",
      "NSCoder",
      "", "", "", "", "", "", "", "",
      "ClosedRange",
      "", "", "", "", "",
      "NSMutableSet",
      "CodeUnit",
      "",
      "Child",
      "", "",
      "Calendar",
      "CloseCode",
      "",
      "UInt32",
      "",
      "NSMutableData",
      "NSMutableArray",
      "NSCalendar",
      "",
      "NSCountedSet",
      "", "", "",
      "UInt16",
      "",
      "Children",
      "",
      "NSUserCancelledError",
      "", "", "",
      "CWideChar",
      "", "", "", "", "", "",
      "NSCondition",
      "", "", "", "", "", "", "",
      "NSMutableDictionary",
      "",
      "NSUnderlineStyle",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "Int",
      "", "", "", "", "", "", "", "",
      "NSMetadataUbiquitousItemIsUploadedKey",
      "",
      "NSUndefinedDateComponent",
      "CountableClosedRange",
      "",
      "Message",
      "",
      "NSMetadataUbiquitousItemIsDownloadedKey",
      "NSMetadataUbiquitousItemIsDownloadingKey",
      "", "",
      "Iterator",
      "NSMetadataUbiquitousItemPercentDownloadedKey",
      "NSMetadataUbiquitousItemIsExternalDocumentKey",
      "", "",
      "NSMetadataUbiquitousItemIsUploadingKey",
      "",
      "CLong",
      "Change",
      "NSMetadataUbiquitousItemContainerDisplayNameKey",
      "",
      "NSMetadataUbiquitousItemHasUnresolvedConflictsKey",
      "", "", "",
      "NSMetadataUbiquitousItemDownloadingErrorKey",
      "NSMetadataUbiquitousItemDownloadingStatusKey",
      "", "", "",
      "NSMetadataUbiquitousItemDownloadingStatusCurrent",
      "", "",
      "NSMetadataUbiquitousItemDownloadingStatusDownloaded",
      "", "",
      "NSMetadataUbiquitousItemDownloadingStatusNotDownloaded",
      "Identifier",
      "", "", "", "", "", "", "",
      "Set",
      "", "", "", "", "", "",
      "State",
      "", "", "",
      "NSMetadataItem",
      "NSSet",
      "",
      "CaseIterable",
      "", "",
      "Int32",
      "UndoManager",
      "Scanner",
      "NSCoding",
      "Magnitude",
      "",
      "Status",
      "InsertionPosition",
      "", "",
      "Int16",
      "Scalar",
      "CUnsignedInt",
      "",
      "CountableRange",
      "", "", "", "",
      "Character",
      "", "",
      "CharacterSet",
      "", "",
      "UInt8",
      "Stride",
      "Unicode",
      "", "",
      "NSMutableString",
      "", "",
      "StrideTo",
      "", "", "", "", "", "", "",
      "NSMetadataItemCityKey",
      "", "",
      "UnitStyle",
      "", "", "", "", "", "", "", "", "",
      "NSNotification",
      "", "", "", "", "",
      "Collection",
      "UInt64",
      "", "",
      "NSUndoManagerGroupIsDiscardableKey",
      "", "",
      "UnicodeCodec",
      "", "", "",
      "NSIndianCalendar",
      "", "", "", "", "", "", "",
      "NSMutableOrderedSet",
      "", "", "", "", "", "", "", "", "",
      "NSMetadataItemContributorsKey",
      "",
      "UnitConcentrationMass",
      "NSMutableIndexSet",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "CalculationError",
      "", "", "", "",
      "NSMetadataItemContentCreationDateKey",
      "", "", "", "",
      "Parser",
      "", "",
      "Port",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "NSMiddleSpecifier",
      "", "", "",
      "String",
      "",
      "CUnsignedLong",
      "", "",
      "Persistence",
      "Pointee",
      "",
      "Int8",
      "", "",
      "NSPoint",
      "NSString",
      "", "", "",
      "Indices",
      "",
      "UnitPower",
      "",
      "PortMessage",
      "UnitPressure",
      "", "", "",
      "SetIterator",
      "",
      "NSJapaneseCalendar",
      "StringProtocol",
      "", "", "", "",
      "NSPointerArray",
      "NSIndexSet",
      "", "", "",
      "Host",
      "Slice",
      "",
      "NSMetadataItemIdentifierKey",
      "",
      "Name",
      "Int64",
      "",
      "NSMetadataUbiquitousItemPercentUploadedKey",
      "", "",
      "Input",
      "",
      "NSPersianCalendar",
      "",
      "NSMetadataItemInstructionsKey",
      "",
      "StrideToIterator",
      "", "", "", "", "", "", "",
      "StringInterpolation",
      "NSMetadataItemInstantMessageAddressesKey",
      "",
      "Numeric",
      "", "",
      "NetService",
      "Result",
      "NSIslamicCalendar",
      "NSMetadataItemMusicalInstrumentNameKey",
      "", "", "",
      "NSMetadataItemMusicalInstrumentCategoryKey",
      "",
      "NSMetadataItemMeteringModeKey",
      "", "", "", "", "", "", "",
      "StaticString",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "Unmanaged",
      "",
      "Measurement",
      "NSMetadataItemStarRatingKey",
      "", "", "", "", "", "", "", "", "",
      "",
      "Progress",
      "", "", "", "", "",
      "NSUserAutomatorTask",
      "", "", "", "", "", "", "", "",
      "SingleValueDecodingContainer",
      "NSSecureCoding",
      "",
      "NSSortDescriptor",
      "",
      "NSSortOptions",
      "",
      "UnsignedInteger",
      "", "",
      "SingleValueEncodingContainer",
      "", "", "",
      "CUnsignedLongLong",
      "", "", "", "", "", "",
      "UnitSpeed",
      "",
      "MessagePort",
      "NSIslamicCivilCalendar",
      "",
      "NSCloseCommand",
      "", "", "", "",
      "NSCountCommand",
      "NSCreateCommand",
      "IteratorProtocol",
      "Process",
      "",
      "NSCloneCommand",
      "Range",
      "", "", "", "", "", "", "",
      "SignedInteger",
      "", "",
      "NSMetadataUbiquitousItemUploadingErrorKey",
      "", "", "", "", "",
      "NSRange",
      "", "", "", "",
      "Regions",
      "", "", "", "", "",
      "NSIndexSetIterator",
      "NSMetadataUbiquitousItemDownloadRequestedKey",
      "",
      "NSMetadataUbiquitousItemURLInLocalContainerKey",
      "",
      "CustomStringConvertible",
      "", "",
      "NSMetadataItemPathKey",
      "", "", "", "", "", "", "",
      "Pipe",
      "Words",
      "NSPredicate",
      "NSMetadataItemPerformersKey",
      "",
      "NonConformingFloatDecodingStrategy",
      "Error",
      "", "", "", "",
      "Event",
      "", "", "",
      "NonConformingFloatEncodingStrategy",
      "", "",
      "NSError",
      "",
      "NSItemProvider",
      "",
      "NSRect",
      "",
      "SpellingState",
      "", "", "",
      "PostingStyle",
      "", "",
      "Properties",
      "Stream",
      "", "", "", "", "", "", "", "", "",
      "NSPositionalSpecifier",
      "",
      "NSPointerFunctions",
      "", "", "",
      "SuspensionID",
      "NSUnicodeStringEncoding",
      "Equatable",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "NameStyle",
      "UnitIlluminance",
      "", "", "",
      "ErrorCode",
      "", "", "", "", "", "", "",
      "RoundingMode",
      "URL",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "UnicodeScalar",
      "",
      "NSXPCConnection",
      "NSNotificationPostToAllSessions",
      "NSMetadataItemColorSpaceKey",
      "", "", "",
      "NSScriptSuiteRegistry",
      "",
      "Repeated",
      "", "", "", "",
      "UnicodeScalarIndex",
      "", "",
      "ProcessInfo",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "Comparator",
      "", "", "", "", "", "", "", "",
      "Component",
      "NSNameSpecifier",
      "",
      "Zip2Sequence",
      "NSNoSpecifierError",
      "", "", "",
      "XMLNode",
      "", "",
      "NSScannedOption",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSXPCConnectionErrorMinimum",
      "", "", "",
      "PadPosition",
      "NSXPCConnectionInvalid",
      "", "", "",
      "NSUserAppleScriptTask",
      "",
      "URLCredential",
      "", "", "", "", "", "",
      "UnitEnergy",
      "ParseResult",
      "", "", "",
      "NS_LittleEndian",
      "", "", "", "", "", "",
      "NSEdgeInsets",
      "", "",
      "URLCredentialStorage",
      "",
      "NSCannotCreateScriptCommandError",
      "", "",
      "NSLoadedClasses",
      "", "", "",
      "StreamDelegate",
      "",
      "NSEdgeInsetsZero",
      "",
      "NSCoderReadCorruptError",
      "",
      "StringTransform",
      "",
      "StringInterpolationProtocol",
      "", "", "", "",
      "Encoder",
      "", "", "",
      "RelativePosition",
      "", "", "", "", "", "", "", "", "",
      "NSMetadataItemResolutionHeightDPIKey",
      "", "", "",
      "CocoaError",
      "", "", "", "", "", "", "", "",
      "Encodable",
      "", "", "", "", "", "", "", "", "",
      "",
      "UnitLength",
      "NSSize",
      "", "", "", "", "", "",
      "Exponent",
      "", "", "",
      "NSMetadataItemRecipientsKey",
      "", "", "", "", "", "", "", "", "",
      "",
      "NSLogicalTest",
      "NSPropertySpecifier",
      "", "", "",
      "NSLocale",
      "",
      "NSMetadataItemRecipientEmailAddressesKey",
      "Locale",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "URLSession",
      "", "",
      "URLCache",
      "UnitElectricCurrent",
      "", "", "", "", "",
      "MeasurementFormatter",
      "", "", "", "", "", "", "", "", "",
      "NSScriptCommand",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "NSMetadataItemHasAlphaChannelKey",
      "", "", "", "", "", "",
      "LocalizedError",
      "", "", "", "", "", "", "", "", "",
      "NSScriptClassDescription",
      "", "", "",
      "Encoding",
      "", "", "",
      "ErrorPointer",
      "",
      "NSErrorPointer",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "CLongLong",
      "", "",
      "Element",
      "Elements",
      "", "", "", "", "", "", "", "", "",
      "SignedNumeric",
      "",
      "NSMetadataItemRecordingYearKey",
      "NSXPCConnectionInterrupted",
      "",
      "URLSessionConfiguration",
      "UIItemProviderPresentationSizeProviding",
      "NSMetadataItemRecordingDateKey",
      "",
      "NSScriptWhoseTest",
      "", "", "", "", "", "", "", "",
      "NSItemProviderReading",
      "", "",
      "NSMetadataItemParticipantsKey",
      "", "", "", "",
      "NSInternalSpecifierError",
      "", "", "",
      "UnitElectricCharge",
      "", "",
      "InputStream",
      "NSEnumerator",
      "",
      "XMLParser",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "XMLParserDelegate",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "CVaListPointer",
      "NSURL",
      "",
      "RunLoop",
      "", "", "", "",
      "NSSetCommand",
      "", "", "",
      "URLResponse",
      "SystemRandomNumberGenerator",
      "Sequence",
      "", "", "", "", "",
      "URLResourceKey",
      "", "", "",
      "NSXPCListener",
      "NSCompoundPredicate",
      "", "", "", "",
      "NSMetadataItemExposureModeKey",
      "",
      "NSComparisonPredicate",
      "NSRandomSpecifier",
      "", "", "", "", "", "",
      "Bool",
      "",
      "NSXPCListenerDelegate",
      "URLResourceValues",
      "NSScriptCoercionHandler",
      "NSCoderErrorMinimum",
      "",
      "Version",
      "", "",
      "NSStreamSOCKSErrorDomain",
      "",
      "ComparisonResult",
      "", "",
      "Value",
      "Values",
      "", "", "", "", "", "", "",
      "Void",
      "", "", "", "",
      "URLComponents",
      "",
      "Bound",
      "NSValue",
      "", "", "", "",
      "Bundle",
      "", "", "", "", "", "", "",
      "JoinedSequence",
      "",
      "LoadHandler",
      "", "", "", "", "", "", "", "", "",
      "",
      "CompletionHandler",
      "", "",
      "CompressionAlgorithm",
      "", "",
      "EnumeratedIterator",
      "",
      "NSCompressionErrorMaximum",
      "", "", "", "", "",
      "NSItemProviderWriting",
      "", "",
      "Date",
      "NSCompressionErrorMinimum",
      "", "", "",
      "Data",
      "",
      "NSMutableCopying",
      "", "", "", "",
      "NSScriptCommandDescription",
      "", "", "", "",
      "NSDate",
      "",
      "Distance",
      "", "",
      "NSData",
      "",
      "NSQuitCommand",
      "", "", "", "", "", "",
      "PersonNameComponents",
      "", "", "", "", "", "", "",
      "EncodedScalar",
      "", "", "",
      "UserDefaults",
      "", "", "",
      "URLProtocol",
      "", "", "", "",
      "NSInternalScriptError",
      "NSPersonNameComponents",
      "CustomNSError",
      "NSDateInterval",
      "", "",
      "ItemReplacementOptions",
      "",
      "PersonNameComponentsFormatter",
      "", "", "", "", "", "",
      "Deallocator",
      "UnitDuration",
      "URLError",
      "",
      "Float",
      "", "",
      "BidirectionalCollection",
      "", "", "",
      "UnitElectricResistance",
      "NSBuddhistCalendar",
      "NSMetadataItemIsUbiquitousKey",
      "", "",
      "URLProtocolClient",
      "",
      "NSCoderValueNotFoundError",
      "NSNoScriptError",
      "",
      "Float32",
      "", "", "", "", "", "",
      "NSPersonNameComponentNickname",
      "EncodingConversionOptions",
      "ReplacingOptions",
      "ProgressReporting",
      "",
      "NSUniqueIDSpecifier",
      "XMLElement",
      "", "", "", "",
      "POSIXError",
      "",
      "Failure",
      "", "",
      "Style",
      "",
      "CGFloat",
      "",
      "CodingKey",
      "NSNotFound",
      "",
      "NS_BigEndian",
      "", "",
      "NSMapEnumerator",
      "NSPersonNameComponentMiddleName",
      "", "", "",
      "NSFilePresenter",
      "",
      "RandomAccessCollection",
      "EnumerationOptions",
      "",
      "UTF32",
      "", "",
      "NSFileVersion",
      "",
      "NSEnumerationOptions",
      "", "", "",
      "UUID",
      "UTF16",
      "",
      "NSFastEnumeration",
      "", "", "", "",
      "Float64",
      "",
      "NSWrapCalendarComponents",
      "UnitsStyle",
      "",
      "NSFastEnumerationState",
      "", "",
      "NSURLConnection",
      "", "",
      "NSFileErrorMaximum",
      "NSCompressionFailedError",
      "",
      "NSUUID",
      "", "", "",
      "NSFastEnumerationIterator",
      "",
      "DateInterval",
      "NSFileErrorMinimum",
      "DistributedNotificationCenter",
      "", "",
      "NSFileCoordinator",
      "", "", "",
      "NSXPCListenerEndpoint",
      "",
      "NSMetadataItemCodecsKey",
      "",
      "CountStyle",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "CenterType",
      "NSFileWriteInvalidFileNameError",
      "", "", "", "", "", "", "", "",
      "RangeExpression",
      "", "", "",
      "SIMD",
      "", "",
      "Decoder",
      "", "", "", "", "", "", "",
      "Dictionary",
      "", "", "", "",
      "SIMD3",
      "", "", "",
      "NSDataDetector",
      "",
      "IteratorSequence",
      "", "", "", "", "",
      "NSDictionary",
      "",
      "Decodable",
      "", "", "", "", "", "",
      "FileManager",
      "", "", "", "",
      "NSURLConnectionDownloadDelegate",
      "", "", "", "", "", "", "",
      "FileManagerDelegate",
      "", "", "", "", "",
      "SIMD2",
      "", "", "", "", "", "", "", "",
      "UTF8",
      "", "", "", "",
      "NSUndoCloseGroupingRunLoopOrdering",
      "",
      "SIMD32",
      "NSPersonNameComponentSuffix",
      "NSClassDescription",
      "", "", "",
      "Float80",
      "", "", "",
      "SIMD16",
      "", "",
      "UnitDispersion",
      "", "", "", "",
      "DateComponents",
      "", "", "",
      "NSURLConnectionDelegate",
      "NSFileSecurity",
      "FlattenSequence",
      "", "",
      "SIMD32Storage",
      "",
      "NSMetadataItemNamedLocationKey",
      "",
      "StringLiteralType",
      "",
      "NSFileManagerUnmountBusyError",
      "",
      "NSURLHandle",
      "",
      "SIMD16Storage",
      "", "", "", "", "",
      "NSCopying",
      "", "", "", "", "", "",
      "CommandLine",
      "", "", "", "", "", "", "", "", "",
      "NSMetadataItemFSCreationDateKey",
      "NetServiceBrowser",
      "EncodingError",
      "", "", "",
      "NSMetadataItemExposureProgramKey",
      "", "",
      "NSFileManagerUnmountDissentingProcessIdentifierErrorKey",
      "NSMetadataItemFSContentChangeDateKey",
      "FlattenCollection",
      "",
      "UnitVolume",
      "", "", "", "", "",
      "NSMetadataItemBitsPerSampleKey",
      "Context",
      "NSCollectionChangeType",
      "", "", "", "", "", "", "",
      "NSPointerToStructHashCallBacks",
      "", "", "", "", "", "", "",
      "DictionaryIterator",
      "", "", "", "",
      "ByteCountFormatter",
      "Kind",
      "SIMD4",
      "NSMetadataItemImageDirectionKey",
      "", "", "", "", "", "", "", "", "",
      "",
      "NSLocalizedFailureReasonErrorKey",
      "", "", "", "",
      "NSPersonNameComponentPrefix",
      "", "", "", "", "", "",
      "Dimension",
      "NSFeatureUnsupportedError",
      "", "", "", "", "", "", "", "", "",
      "",
      "UnicodeDecodingResult",
      "", "", "",
      "SIMD8",
      "", "",
      "VolumeEnumerationOptions",
      "", "",
      "SIMDStorage",
      "", "", "", "",
      "NSDateComponents",
      "", "",
      "NSSolarisOperatingSystem",
      "", "", "", "", "", "",
      "NSDecimalNoScale",
      "", "", "", "", "",
      "NSMetadataItemDurationSecondsKey",
      "NSFileLockingError",
      "", "",
      "ContentKind",
      "NSFileWriteInapplicableStringEncodingError",
      "", "", "",
      "SIMD64",
      "", "", "", "", "", "", "",
      "Formatter",
      "", "", "", "", "",
      "CChar",
      "",
      "PortDelegate",
      "URLProtectionSpace",
      "Index",
      "", "",
      "CChar16",
      "", "",
      "NSDeleteCommand",
      "CShort",
      "DisplayStyle",
      "SIMD64Storage",
      "", "", "",
      "CChar32",
      "", "", "",
      "RangeReplaceableCollection",
      "NSUnarchiver",
      "MassFormatter",
      "",
      "NSMetadataUbiquitousItemIsSharedKey",
      "Thread",
      "", "", "",
      "NetServiceBrowserDelegate",
      "", "", "", "", "", "", "", "",
      "NSPropertyListReadStreamError",
      "FileHandle",
      "", "", "",
      "NSUserUnixTask",
      "",
      "NSFileProviderService",
      "", "",
      "NSURLErrorCancelled",
      "", "", "", "",
      "NSSwappedFloat",
      "", "", "", "",
      "NSMutableURLRequest",
      "", "", "", "", "",
      "NSFileProviderServiceName",
      "",
      "NSJapaneseEUCStringEncoding",
      "", "", "", "", "", "", "", "", "",
      "NSChineseCalendar",
      "NSFileWriteNoPermissionError",
      "", "", "",
      "UnicodeScalarType",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "FloatingPoint",
      "NSURLErrorCannotMoveFile",
      "NSURLComponents",
      "NSMetadataItemKindKey",
      "", "", "", "", "", "",
      "NetServiceDelegate",
      "", "",
      "NSIntMapValueCallBacks",
      "Decimal",
      "StoragePolicy",
      "", "", "", "", "", "", "", "",
      "NSURLErrorUserCancelledAuthentication",
      "NSErrorDomain",
      "", "", "",
      "FloatingPointSign",
      "",
      "NSMetadataItemCreatorKey",
      "", "",
      "SIMD2Storage",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSMetadataItemCountryKey",
      "SIMDScalar",
      "", "", "", "",
      "EnergyFormatter",
      "", "",
      "NSMetadataItemRightsKey",
      "", "", "", "",
      "NSMetadataUbiquitousSharedItemCurrentUserRoleKey",
      "NSMetadataUbiquitousSharedItemPermissionsReadOnly",
      "NSMetadataUbiquitousSharedItemPermissionsReadWrite",
      "", "",
      "NSFileAccessIntent",
      "NSMetadataUbiquitousSharedItemRoleOwner",
      "NSMetadataUbiquitousSharedItemCurrentUserPermissionsKey",
      "",
      "NSMetadataUbiquitousSharedItemOwnerNameComponentsKey",
      "NSMetadataUbiquitousSharedItemMostRecentEditorNameComponentsKey",
      "",
      "NSMetadataUbiquitousSharedItemRoleParticipant",
      "", "",
      "NSFileWriteUnsupportedSchemeError",
      "", "", "", "", "", "",
      "NSMetadataQuery",
      "NSProxy",
      "unichar",
      "", "", "",
      "CSignedChar",
      "NSArray",
      "CUnsignedChar",
      "CUnsignedShort",
      "", "",
      "NSCache",
      "", "", "", "", "", "",
      "ResponseDisposition",
      "NSMachPort",
      "", "", "", "", "", "",
      "CVarArg",
      "UnitArea",
      "", "", "",
      "IndexSet",
      "NSFilePathErrorKey",
      "",
      "Never",
      "",
      "UnicodeScalarView",
      "AllCases",
      "NSCharacterSet",
      "CountablePartialRangeFrom",
      "",
      "SetIndex",
      "",
      "NSMetadataItemWhiteBalanceKey",
      "NSMetadataItemFinderCommentKey",
      "", "", "",
      "UnitAngle",
      "URLRequest",
      "",
      "NSMachErrorDomain",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "Tuple",
      "", "", "",
      "NSURLQueryItem",
      "",
      "NSMutableCharacterSet",
      "SIMD4Storage",
      "NSAssertionHandler",
      "", "",
      "NSAssertionHandlerKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "NSMetadataQueryAttributeValueTuple",
      "", "", "",
      "NSCoderInvalidValueError",
      "", "", "", "", "", "",
      "NSMetadataItemURLKey",
      "", "", "", "",
      "UnitTemperature",
      "NSFileReadCorruptFileError",
      "SIMD8Storage",
      "UnitConverter",
      "", "",
      "NSMetadataItemLanguagesKey",
      "", "", "", "",
      "swift",
      "", "", "", "", "", "", "", "",
      "IndexingIterator",
      "", "", "",
      "UnitConverterLinear",
      "",
      "NSMetadataItemLensModelKey",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSMetadataQueryDelegate",
      "",
      "Operator",
      "NSMetadataItemLongitudeKey",
      "NSMetadataItemContactKeywordsKey",
      "",
      "UnsafePointer",
      "", "", "", "", "", "",
      "Operation",
      "", "",
      "Options",
      "", "", "", "", "",
      "BiquadFunctions",
      "Hasher",
      "ProgressKind",
      "Notification",
      "", "",
      "OptionSet",
      "", "", "", "", "",
      "NSLocalizedRecoverySuggestionErrorKey",
      "",
      "UnicodeScalarLiteralType",
      "Optional",
      "",
      "NSIntegerHashCallBacks",
      "",
      "Modifier",
      "", "", "", "", "", "",
      "OperationQueue",
      "", "", "",
      "Timer",
      "", "", "",
      "NSOrderedSet",
      "", "",
      "NSNotificationDeliverImmediately",
      "TimeZone",
      "", "", "", "", "", "", "", "", "",
      "",
      "NotificationCenter",
      "", "", "", "", "",
      "NSConditionLock",
      "NSHashEnumerator",
      "", "",
      "NSMetadataItemLastUsedDateKey",
      "UnfoldFirstSequence",
      "", "",
      "NSRegularExpression",
      "", "", "", "",
      "AutoreleasingUnsafeMutablePointer",
      "",
      "NSTimeZone",
      "",
      "DictionaryLiteral",
      "", "", "", "", "", "", "", "",
      "UnitAcceleration",
      "", "", "", "", "", "", "",
      "NSUserActivity",
      "",
      "NSMetadataItemPixelCountKey",
      "", "", "", "", "", "", "", "",
      "NSItemProviderFileOptions",
      "NSUserScriptTask",
      "",
      "DecodingError",
      "", "", "", "", "", "", "", "",
      "TerminationReason",
      "NSMetadataItemProfileNameKey",
      "", "",
      "PartialRangeFrom",
      "NSMetadataItemAuthorAddressesKey",
      "",
      "CDouble",
      "ASCII",
      "", "", "", "", "", "", "", "", "",
      "NSBundleErrorMaximum",
      "SchedulerOptions",
      "", "",
      "Codable",
      "",
      "NSIndexPath",
      "",
      "QueuePriority",
      "NSMetadataItemAudioChannelCountKey",
      "NSBundleErrorMinimum",
      "", "",
      "NSBundleResourceRequest",
      "", "", "", "",
      "NSValidationErrorMinimum",
      "Body",
      "NSMetadataItemHeadlineKey",
      "", "", "", "", "", "",
      "NSMetadataItemMediaTypesKey",
      "",
      "NSGregorianCalendar",
      "", "", "", "", "",
      "EmptyCollection",
      "MaskStorage",
      "", "", "",
      "NSMetadataItemComposerKey",
      "", "", "",
      "NSMetadataItemCommentKey",
      "", "", "", "",
      "NSUserNotification",
      "FloatingPointRoundingRule",
      "", "", "",
      "NSBundleResourceRequestLoadingPriorityUrgent",
      "NSMetadataItemResolutionWidthDPIKey",
      "NSXPCConnectionErrorMaximum",
      "LanguageDirection",
      "", "", "", "",
      "TimeInterval",
      "NotificationCoalescing",
      "NSMetadataItemMusicalGenreKey",
      "NSUserNotificationCenter",
      "", "",
      "URLSessionDelegate",
      "", "", "", "",
      "NSUserNotificationCenterDelegate",
      "",
      "CanonicalCombiningClass",
      "NSDecimalMaxSize",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "EnumeratedSequence",
      "", "", "", "", "",
      "PartialKeyPath",
      "",
      "NSDecompressionFailedError",
      "",
      "Output",
      "", "",
      "NSHPUXOperatingSystem",
      "",
      "NSWritingDirectionFormatType",
      "", "",
      "RawRepresentable",
      "NSFileReadNoPermissionError",
      "", "",
      "SearchDirection",
      "",
      "NSFormattingError",
      "", "", "", "", "", "", "",
      "NSPropertyListReadCorruptError",
      "", "",
      "UnitOptions",
      "OutputStream",
      "",
      "NSMetadataItemContentModificationDateKey",
      "ThermalState",
      "AddingOptions",
      "",
      "NSMetadataItemProjectsKey",
      "UnboundedRange",
      "",
      "SearchOptions",
      "URLSessionStreamDelegate",
      "NSMetadataItemProducerKey",
      "",
      "NSXPCProxyCreating",
      "", "", "",
      "FileWrapper",
      "UnboundedRange_",
      "OutputFormatting",
      "",
      "NSException",
      "", "",
      "NSMetadataQueryLocalComputerScope",
      "JSONSerialization",
      "",
      "NSPropertyListErrorMinimum",
      "NSURLErrorSecureConnectionFailed",
      "",
      "NSExceptionName",
      "", "",
      "NSURLRequest",
      "",
      "NSURLErrorUnsupportedURL",
      "NSMetadataItemTimeSignatureKey",
      "", "", "", "", "", "", "", "",
      "NSURLErrorRedirectToNonExistentLocation",
      "", "", "",
      "BinaryInteger",
      "",
      "NSExtensionRequestHandling",
      "NSExpression",
      "",
      "NSTimeIntervalSince1970",
      "NSURLErrorCancelledReasonUserForceQuitApplication",
      "", "", "", "",
      "NSURLErrorCannotConnectToHost",
      "", "",
      "Strideable",
      "",
      "NSMetadataItemEditorsKey",
      "", "",
      "NSCollectorDisabledOption",
      "NSSaveOptions",
      "",
      "SocketPort",
      "",
      "NSFileReadUnsupportedSchemeError",
      "NSMoveCommand",
      "", "", "",
      "NSMetadataItemLayerNamesKey",
      "", "", "", "", "", "", "", "", "",
      "",
      "ReversedCollection",
      "",
      "NSMetadataItemEXIFGPSVersionKey",
      "",
      "NSExecutableNotLoadableError",
      "", "", "", "",
      "NSMetadataItemOrganizationsKey",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "_AppendKeyPath",
      "", "", "", "", "", "",
      "NSURLErrorCannotLoadFromNetwork",
      "", "", "",
      "NSIntegerMapValueCallBacks",
      "UnitElectricPotentialDifference",
      "NSMetadataItemWhereFromsKey",
      "",
      "LazyCollection",
      "", "", "",
      "NSCocoaErrorDomain",
      "MutableCollection",
      "NSMetadataItemRecipientAddressesKey",
      "", "", "", "",
      "NSUserNotificationAction",
      "NSMetadataItemGPSMeasureModeKey",
      "NSMutableAttributedString",
      "",
      "MachError",
      "", "", "", "", "", "",
      "Substring",
      "NSMetadataItemIsApplicationManagedKey",
      "",
      "NSURLErrorCannotParseResponse",
      "NSMetadataItemLatitudeKey",
      "", "", "", "",
      "NSMetadataItemLyricistKey",
      "NSMetadataItemGPSProcessingMethodKey",
      "",
      "NSURLErrorNoPermissionsToReadFile",
      "", "",
      "Publisher",
      "", "", "", "",
      "XMLDocument",
      "NSMetadataItemPageHeightKey",
      "", "", "", "", "",
      "NSMetadataItemOriginalSourceKey",
      "", "", "",
      "NSMetadataItemFocalLength35mmKey",
      "", "",
      "LengthFormatter",
      "", "", "", "", "",
      "Published",
      "NSURLErrorCancelledReasonInsufficientSystemResources",
      "", "", "", "", "", "", "", "", "",
      "",
      "SendOptions",
      "", "", "", "",
      "NSMetadataItemEXIFVersionKey",
      "", "",
      "NSPersonNameComponentFamilyName",
      "AcceptPolicy",
      "", "", "", "",
      "URLFileProtection",
      "", "", "", "", "", "", "",
      "NSURLFileScheme",
      "",
      "NSProprietaryStringEncoding",
      "",
      "NSUserActivityPersistentIdentifier",
      "NSNumber",
      "NSContainerSpecifierError",
      "", "", "", "", "", "", "", "",
      "NSItemProviderPreferredImageSizeKey",
      "",
      "NumberFormatter",
      "",
      "NSExtensionItem",
      "", "", "", "",
      "NSGrammarRange",
      "", "", "",
      "NSMetadataItemFSNameKey",
      "URLSessionTask",
      "NSHelpAnchorErrorKey",
      "NSMetadataItemDateAddedKey",
      "",
      "NSFileWriteUnknownError",
      "", "", "",
      "NSProtocolChecker",
      "",
      "MatchingPolicy",
      "", "",
      "NSURLConnectionDataDelegate",
      "",
      "NSRelativeSpecifier",
      "", "", "",
      "NSSpellServer",
      "", "", "", "",
      "NSScriptExecutionContext",
      "NSExistsCommand",
      "",
      "PartialRangeUpTo",
      "", "", "", "", "",
      "PreferredPresentationStyle",
      "",
      "BinaryFloatingPoint",
      "NSRecursiveLock",
      "NSSpellServerDelegate",
      "",
      "NSMetadataItemApplicationCategoriesKey",
      "PartialRangeThrough",
      "", "",
      "NSCloudSharingConflictError",
      "",
      "WriteOptions",
      "", "", "",
      "NSCoderErrorMaximum",
      "", "", "",
      "NSPurgeableData",
      "", "",
      "LazyMapSequence",
      "DateIntervalFormatter",
      "URLQueryItem",
      "Key",
      "Keys",
      "", "",
      "MemoryLayout",
      "",
      "NSISO8601Calendar",
      "", "", "", "", "", "",
      "NSASCIIStringEncoding",
      "",
      "ReverseParser",
      "",
      "NSGrammarCorrections",
      "URLAuthenticationChallenge",
      "", "", "",
      "NSPropertyListWriteStreamError",
      "",
      "URLAuthenticationChallengeSender",
      "", "", "", "", "", "", "", "",
      "NSSpecifierTest",
      "", "", "", "",
      "NSMetadataItemDownloadedDateKey",
      "", "",
      "NSMetadataItemPublishersKey",
      "NSLinguisticTag",
      "NSMetadataItemPixelWidthKey",
      "LazyMapCollection",
      "NSLinguisticTagger",
      "", "", "", "", "", "", "",
      "NSLocalizedFailureErrorKey",
      "",
      "JSONEncoder",
      "", "", "", "",
      "NSMetadataQueryUserHomeScope",
      "", "", "", "", "", "", "", "",
      "NSLinguisticTaggerUnit",
      "ReadOptions",
      "", "",
      "NSMetadataItemEmailAddressesKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "RawValue",
      "", "", "",
      "UnmountOptions",
      "", "", "",
      "NSXPCInterface",
      "NSCloudSharingNoPermissionError",
      "", "",
      "NSFormattingErrorMinimum",
      "",
      "ReadingOptions",
      "", "", "", "", "",
      "DropFirstSequence",
      "", "", "", "", "", "", "", "",
      "NSMetadataItemExposureTimeSecondsKey",
      "AncestorRepresentation",
      "", "", "", "", "",
      "NSMetadataItemFSSizeKey",
      "", "", "", "",
      "NotificationQueue",
      "",
      "NSNonOwnedPointerOrNullMapKeyCallBacks",
      "", "", "", "", "", "",
      "LazySequence",
      "DateComponentsFormatter",
      "ExpressionType",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "NSPersonNameComponentKey",
      "", "", "", "",
      "NSMetadataItemStateOrProvinceKey",
      "",
      "URLSessionTaskMetrics",
      "",
      "NSAppleScript",
      "NSBinarySearchingOptions",
      "",
      "NSURLErrorZeroByteResource",
      "NumberRepresentation",
      "", "", "",
      "UserInfoKey",
      "Comparable",
      "", "", "", "",
      "NSIndexSpecifier",
      "ForwardParser",
      "", "", "", "", "", "",
      "NSOperationNotSupportedForKeyException",
      "NSLock",
      "", "", "", "",
      "NSNoTopLevelContainersSpecifierError",
      "NSRepublicOfChinaCalendar",
      "", "",
      "NSPersonNameComponentDelimiter",
      "", "",
      "RangeView",
      "", "", "",
      "NSOperationNotSupportedForKeyScriptError",
      "", "", "", "", "",
      "NSMetadataItemVideoBitRateKey",
      "NSReceiversCantHandleCommandScriptError",
      "", "",
      "NSGetCommand",
      "", "",
      "NSUnderlyingErrorKey",
      "", "", "", "", "", "",
      "CustomLeafReflectable",
      "", "", "", "",
      "NSArgumentsWrongScriptError",
      "DateFormatter",
      "",
      "NSUserNotificationDefaultSoundName",
      "NSArgumentEvaluationScriptError",
      "", "",
      "NSWindowsCP1250StringEncoding",
      "",
      "WritingOptions",
      "",
      "NSMetadataItemVersionKey",
      "NSWindowsCP1251StringEncoding",
      "", "", "", "",
      "NSMetadataItemGPSDateStampKey",
      "", "", "", "",
      "NSWindowsCP1253StringEncoding",
      "", "",
      "IndexDistance",
      "IntegerLiteralType",
      "NSGrammarUserDescription",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "OpaquePointer",
      "", "", "",
      "DirectoryEnumerator",
      "", "", "", "", "", "", "", "",
      "Any",
      "", "", "", "", "",
      "NSWindowsCP1252StringEncoding",
      "", "", "", "",
      "PublishingHandler",
      "Array",
      "", "", "", "", "", "", "",
      "StringEncodingDetectionOptionsKey",
      "", "", "", "", "", "", "", "", "",
      "",
      "NSMetadataItemStreamableKey",
      "",
      "NSMetadataItemNumberOfPagesKey",
      "NSMetadataItemExecutableArchitecturesKey",
      "NSURLErrorCannotDecodeContentData",
      "", "", "", "", "",
      "NSMetadataItemDueDateKey",
      "NSFileReadNoSuchFileError",
      "CompareOptions",
      "", "",
      "NSLocking",
      "", "", "",
      "NSExtensionJavaScriptPreprocessingResultsKey",
      "",
      "NSMetadataItemDirectorKey",
      "",
      "KeyPath",
      "NSMetadataItemDisplayNameKey",
      "", "", "", "",
      "AnyClass",
      "", "", "",
      "NSMetadataItemAcquisitionMakeKey",
      "", "", "",
      "NSCloudSharingErrorMinimum",
      "LazyCollectionProtocol",
      "",
      "NSURLErrorCannotFindHost",
      "",
      "NSURLErrorCannotCreateFile",
      "SchedulerTimeType",
      "NSMetadataItemDescriptionKey",
      "", "", "", "", "", "",
      "NSURLErrorCannotCloseFile",
      "", "", "",
      "NSMetadataItemKeySignatureKey",
      "URLRelationship",
      "", "", "", "",
      "NSOperationNotSupportedForKeySpecifierError",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "NSMetadataItemFNumberKey",
      "", "",
      "NSMetadataItemEncodingApplicationsKey",
      "", "", "",
      "DecodingFailurePolicy",
      "", "", "", "", "", "",
      "NSMacOSRomanStringEncoding",
      "", "", "", "", "",
      "NSWindowsCP1254StringEncoding",
      "", "",
      "NSMetadataItemSpeedKey",
      "", "", "", "", "",
      "NSOSStatusErrorDomain",
      "", "", "",
      "LosslessStringConvertible",
      "", "",
      "NSCacheDelegate",
      "", "", "", "", "", "", "", "", "",
      "",
      "NSMetadataItemPhoneNumbersKey",
      "", "", "",
      "UnfoldSequence",
      "",
      "NSMetadataItemGPSDestLatitudeKey",
      "", "",
      "NSMetadataItemCFBundleIdentifierKey",
      "", "", "", "", "",
      "NSMetadataItemAudioEncodingApplicationKey",
      "",
      "NSStreamSocketSSLErrorDomain",
      "", "", "", "", "",
      "DictionaryIndex",
      "",
      "AnyIterator",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "NSIntMapKeyCallBacks",
      "", "", "", "",
      "GeneralCategory",
      "", "", "", "",
      "DateEncodingStrategy",
      "", "",
      "NSFileReadTooLargeError",
      "",
      "DataEncodingStrategy",
      "", "", "",
      "PropertyListEncoder",
      "LazySequenceProtocol",
      "",
      "NSURLErrorBackgroundSessionWasDisconnected",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "NSURLErrorBackgroundSessionRequiresSharedContainer",
      "", "", "", "",
      "ContiguousArray",
      "FileAttributeKey",
      "", "", "", "", "",
      "NSRangeSpecifier",
      "NSExtensionItemAttachmentsKey",
      "", "",
      "NSURLErrorBadURL",
      "", "", "", "",
      "NSUserActivityErrorMinimum",
      "NSURLErrorBackgroundTaskCancelledReasonKey",
      "", "", "",
      "NumericType",
      "", "", "", "",
      "NSURLErrorRequestBodyStreamExhausted",
      "", "", "", "", "", "", "",
      "CustomPlaygroundDisplayConvertible",
      "",
      "NSMetadataItemAudiencesKey",
      "DirectoryEnumerationOptions",
      "", "",
      "PropertyListSerialization",
      "", "",
      "AnyCollection",
      "NetworkUnavailableReason",
      "", "",
      "CachedURLResponse",
      "", "", "", "",
      "UnsafeRawPointer",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSMachPortDelegate",
      "", "", "", "", "", "", "", "", "",
      "UnitFrequency",
      "NSMetadataItemAppleLoopsRootKeyKey",
      "NSPersonNameComponentGivenName",
      "",
      "NSMetadataItemAppleLoopDescriptorsKey",
      "",
      "ManagedBuffer",
      "NSMetadataItemAppleLoopsKeyFilterTypeKey",
      "NSMetadataItemCopyrightKey",
      "",
      "NSCloudSharingNetworkFailureError",
      "",
      "NSURLErrorCancelledReasonBackgroundUpdatesDisabled",
      "NSURLErrorDomain",
      "", "", "", "",
      "NSLinguisticTagScheme",
      "",
      "MatchingFlags",
      "", "",
      "RandomNumberGenerator",
      "NSISO2022JPStringEncoding",
      "JSONDecoder",
      "", "", "", "",
      "NSURLCredentialStorageRemoveSynchronizableCredentials",
      "", "",
      "ManagedBufferPointer",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "URLSessionDataDelegate",
      "", "", "", "",
      "NSFileReadUnknownError",
      "Double",
      "", "", "", "", "", "", "", "", "",
      "RepeatedTimePolicy",
      "", "",
      "CachePolicy",
      "", "", "", "", "", "", "",
      "NSStringEncodingErrorKey",
      "NSLocalizedDescriptionKey",
      "NSReceiverEvaluationScriptError",
      "", "", "", "",
      "NSUTF16StringEncoding",
      "", "", "", "", "",
      "NSMetadataItemMaxApertureKey",
      "", "", "",
      "NSUTF32StringEncoding",
      "NSUserActivityDelegate",
      "", "",
      "ArraySlice",
      "", "",
      "NSExecutableErrorMinimum",
      "", "", "", "", "", "", "",
      "NSURLErrorCannotRemoveFile",
      "NSMetadataItemAudioSampleRateKey",
      "SubSequence",
      "",
      "DefaultIndices",
      "", "",
      "NSFileHandleNotificationDataItem",
      "", "", "", "", "",
      "NSNonLossyASCIIStringEncoding",
      "", "",
      "NSFileHandleNotificationMonitorModes",
      "", "", "", "", "", "", "", "",
      "NSExecutableRuntimeMismatchError",
      "", "", "", "",
      "NSMetadataItemSecurityMethodKey",
      "", "", "",
      "NSItemProviderRepresentationVisibility",
      "NSPropertyListReadUnknownVersionError",
      "",
      "SIMDMask",
      "NSMetadataItemTotalBitRateKey",
      "", "", "", "",
      "NSFileHandleNotificationFileHandleItem",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "NSTextWritingDirection",
      "", "", "", "", "", "", "", "", "",
      "",
      "NSURLErrorNotConnectedToInternet",
      "NSMetadataItemCameraOwnerKey",
      "", "", "", "", "",
      "URLFileResourceType",
      "",
      "CollectionDifference",
      "NSCloudSharingQuotaExceededError",
      "", "",
      "NSFileWriteFileExistsError",
      "NSMetadataItemPageWidthKey",
      "", "",
      "SearchPathDirectory",
      "",
      "URLSessionDownloadDelegate",
      "NSISOLatin1StringEncoding",
      "", "", "", "", "", "", "",
      "HTTPURLResponse",
      "", "", "", "", "", "", "",
      "CLongDouble",
      "", "", "", "", "", "", "", "",
      "NSRecoveryAttempterErrorKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "NSUncaughtExceptionHandler",
      "", "", "", "", "", "", "", "", "",
      "",
      "NSISOLatin2StringEncoding",
      "NSURLDownload",
      "", "",
      "NSMetadataItemGPSStatusKey",
      "", "", "", "",
      "NSMetadataItemGPSDestBearingKey",
      "", "", "", "", "",
      "HMCharacteristicPropertySupportsEvent",
      "", "", "",
      "NSURLDownloadDelegate",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "NSFileNoSuchFileError",
      "NSDecimalNumber",
      "", "", "", "", "", "", "", "", "",
      "NSNonOwnedPointerHashCallBacks",
      "FileProtectionType",
      "", "", "", "",
      "StrideThrough",
      "", "", "",
      "NSDiscardableContent",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "NSExecutableLoadError",
      "", "",
      "NSMetadataItemIsGeneralMIDISequenceKey",
      "NSDecimalNumberHandler",
      "NSExecutableLinkError",
      "NSLocalizedRecoveryOptionsErrorKey",
      "", "", "", "",
      "StrideThroughIterator",
      "", "", "", "", "", "",
      "PropertyListFormat",
      "FileOperationKind",
      "", "", "", "",
      "NSMetadataItemAudioBitRateKey",
      "", "", "",
      "Base64DecodingOptions",
      "", "", "",
      "DefaultStringInterpolation",
      "",
      "KeyEncodingStrategy",
      "", "",
      "NSMetadataItemGPSDestDistanceKey",
      "Base64EncodingOptions",
      "SIMDMaskScalar",
      "",
      "NSURLSessionTransferSizeUnknown",
      "", "", "", "", "",
      "KeyedEncodingContainer",
      "", "", "", "", "",
      "UTF16View",
      "",
      "NSDateComponentUndefined",
      "", "", "",
      "NSMetadataItemAuthorsKey",
      "NSMetadataItemApertureKey",
      "", "", "",
      "ReferenceType",
      "", "", "", "", "",
      "NSMetadataItemAltitudeKey",
      "",
      "NSURLErrorUnknown",
      "", "", "",
      "NSFileReadUnknownStringEncodingError",
      "", "", "", "", "", "", "",
      "NSUserActivityRemoteApplicationTimedOutError",
      "",
      "NSExtensionContext",
      "", "", "", "", "", "",
      "IndexPath",
      "", "",
      "FixedWidthInteger",
      "DropWhileSequence",
      "NSBundleExecutableArchitecturePPC",
      "",
      "NSBundleExecutableArchitecturePPC64",
      "", "", "",
      "ExternalEntityResolvingPolicy",
      "", "",
      "NSXPCConnectionReplyInvalid",
      "", "", "", "",
      "NSValidationErrorMaximum",
      "",
      "OperatingSystemVersion",
      "", "", "", "", "",
      "NSMetadataItemCoverageKey",
      "", "",
      "NSUnknownKeyScriptError",
      "",
      "LazyFilterCollection",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "DocumentType",
      "BooleanLiteralType",
      "", "",
      "NSWindows95OperatingSystem",
      "", "", "",
      "DateDecodingStrategy",
      "NSBundleExecutableArchitectureX86_64",
      "NSURLErrorCallIsActive",
      "", "",
      "DataDecodingStrategy",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "PropertyListDecoder",
      "", "", "", "", "", "",
      "LogicalType",
      "",
      "URLSessionDataTask",
      "NSURLSessionDownloadTaskResumeData",
      "",
      "NSURLErrorCannotOpenFile",
      "NSURLErrorFailingURLPeerTrustErrorKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "URLSessionTaskDelegate",
      "", "", "",
      "NSURLErrorClientCertificateRequired",
      "",
      "NSURLErrorTimedOut",
      "NSNonOwnedPointerMapKeyCallBacks",
      "",
      "NSURLErrorClientCertificateRejected",
      "UTF8View",
      "NSHebrewCalendar",
      "", "", "", "", "", "", "",
      "NSErrorFailingURLStringKey",
      "", "", "", "",
      "NSURLErrorUserAuthenticationRequired",
      "", "", "", "", "",
      "NSSwappedDouble",
      "", "", "",
      "NSMACHOperatingSystem",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSMetadataItemGPSDOPKey",
      "MutableURLRequest",
      "NSMetadataItemOrientationKey",
      "", "", "",
      "UnkeyedEncodingContainer",
      "NSPropertyListErrorMaximum",
      "", "", "", "", "", "", "", "", "",
      "",
      "NSMetadataQueryResultContentRelevanceAttribute",
      "", "", "", "", "", "", "",
      "NSURLErrorInternationalRoamingOff",
      "", "", "", "", "", "",
      "FloatLiteralType",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "NSBundleExecutableArchitectureI386",
      "",
      "NSURLErrorNetworkConnectionLost",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "NSURLErrorFailingURLStringErrorKey",
      "", "", "", "", "", "", "", "",
      "NSURLProtectionSpaceFTP",
      "NSExtensionJavaScriptFinalizeArgumentKey",
      "", "", "", "", "", "", "", "",
      "NSURLProtectionSpaceFTPProxy",
      "",
      "DelayedRequestDisposition",
      "", "",
      "NSMetadataItemOriginalFormatKey",
      "", "", "",
      "NSURLErrorServerCertificateUntrusted",
      "", "", "", "",
      "DTDKind",
      "", "", "",
      "NSPropertyListWriteInvalidError",
      "NSFileWriteVolumeReadOnlyError",
      "",
      "NSURLErrorServerCertificateNotYetValid",
      "", "", "",
      "NSOwnedPointerMapValueCallBacks",
      "",
      "NSKeyValueChange",
      "",
      "NSMetadataItemISOSpeedKey",
      "", "", "",
      "NSMetadataQueryUpdateChangedItemsKey",
      "", "", "",
      "RawExponent",
      "", "",
      "NSURLErrorServerCertificateHasBadDate",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "NSURLErrorCannotWriteToFile",
      "", "", "", "", "", "", "",
      "KeyedEncodingContainerProtocol",
      "", "",
      "FloatingPointClassification",
      "",
      "AnyRandomAccessCollection",
      "", "", "", "", "", "",
      "NSNonRetainedObjectMapValueCallBacks",
      "", "", "",
      "AnySequence",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSCloudSharingTooManyParticipantsError",
      "",
      "NSFileReadInvalidFileNameError",
      "", "",
      "NSMetadataItemFocalLengthKey",
      "", "", "", "", "", "",
      "TestComparisonOperation",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "MatchingOptions",
      "", "", "",
      "NSUnknownKeySpecifierError",
      "", "", "", "",
      "NSMetadataItemTimestampKey",
      "", "", "", "", "", "", "",
      "NSMetadataQueryUpdateAddedItemsKey",
      "", "", "", "", "", "", "",
      "ISO8601DateFormatter",
      "", "", "", "",
      "ExpressibleByArrayLiteral",
      "", "", "", "",
      "NSMapTable",
      "NSMetadataItemAcquisitionModelKey",
      "", "", "", "", "", "", "", "",
      "ExpressibleByFloatLiteral",
      "NSFileReadInapplicableStringEncodingError",
      "ExpressibleByIntegerLiteral",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "KeyValuePairs",
      "",
      "ExpressibleByBooleanLiteral",
      "", "",
      "NSMetadataItemFontsKey",
      "",
      "NSURLErrorDataNotAllowed",
      "", "",
      "NSObject",
      "",
      "NSMetadataQueryIndexedLocalComputerScope",
      "", "", "", "", "",
      "NSUTF8StringEncoding",
      "", "", "",
      "NSMetadataItemIsLikelyJunkKey",
      "NSMetadataItemGPSAreaInformationKey",
      "NSMetadataQueryResultGroup",
      "", "", "", "", "", "",
      "UnsafeMutablePointer",
      "",
      "Hashable",
      "", "", "", "",
      "RawSignificand",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "DFTFunctions",
      "NSHashTable",
      "", "", "", "",
      "DateTimeStyle",
      "",
      "ProgressUserInfoKey",
      "", "", "",
      "DocumentReadingOptionKey",
      "", "", "", "", "", "", "",
      "NSMetadataItemPixelHeightKey",
      "NSMetadataItemGPSDestLongitudeKey",
      "", "", "", "", "",
      "NSMetadataItemDeliveryTypeKey",
      "", "", "", "",
      "NSURLErrorResourceUnavailable",
      "", "", "", "", "", "",
      "MutabilityOptions",
      "NSHashTableCallBacks",
      "",
      "ArrayLiteralElement",
      "StreamSocketSecurityLevel",
      "", "", "", "", "", "", "",
      "NSMetadataItemAttributeChangeDateKey",
      "KeyDecodingStrategy",
      "NSMetadataItemRedEyeOnOffKey",
      "", "", "", "", "", "", "", "",
      "ObjectIdentifier",
      "NSAttributedString",
      "", "",
      "NSMetadataItemGPSMapDatumKey",
      "NSMetadataQueryAccessibleUbiquitousExternalDocumentsScope",
      "", "", "",
      "NSFormattingErrorMaximum",
      "ExpressibleByStringInterpolation",
      "", "",
      "KeyedDecodingContainer",
      "", "", "", "", "",
      "NSURLErrorBackgroundSessionInUseByAnotherProcess",
      "", "", "", "", "", "", "", "",
      "FileAttributeType",
      "",
      "UnitFuelEfficiency",
      "", "",
      "CheckingType",
      "", "", "", "", "", "", "", "",
      "NSMetadataItemSubjectKey",
      "", "", "", "",
      "AffineTransform",
      "", "", "", "", "",
      "NSURLProtectionSpaceSOCKSProxy",
      "", "",
      "NSURLErrorFileIsDirectory",
      "", "", "",
      "CollectionOfOne",
      "", "", "", "", "", "", "", "",
      "NSURLErrorKey",
      "PlaygroundQuickLook",
      "NSMetadataItemExposureTimeStringKey",
      "",
      "NSMetadataQueryNetworkScope",
      "", "", "",
      "NSURLErrorDownloadDecodingFailedMidStream",
      "", "", "", "", "", "", "", "", "",
      "PropertyKey",
      "URLSessionTaskTransactionMetrics",
      "", "", "", "",
      "SetAlgebra",
      "NSFileWriteOutOfSpaceError",
      "NSInvalidIndexSpecifierError",
      "", "", "", "",
      "NSMetadataItemInformationKey",
      "", "", "",
      "NSExtensionItemAttributedContentTextKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "UnsafeBufferPointer",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSMetadataItemAuthorEmailAddressesKey",
      "", "", "", "", "", "", "", "",
      "AnyBidirectionalCollection",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "NSMetadataItemGPSDifferentalKey",
      "", "", "", "",
      "ResourceFetchType",
      "", "", "", "", "", "", "",
      "NSMetadataItemKeywordsKey",
      "", "", "", "",
      "HTTPCookie",
      "", "",
      "LazyDropWhileCollection",
      "", "", "", "", "",
      "UnkeyedDecodingContainer",
      "",
      "NSMetadataQueryUpdateRemovedItemsKey",
      "", "", "", "", "", "", "", "",
      "NSHashTableOptions",
      "",
      "NSRequiredArgumentsMissingScriptError",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "ZeroFormattingBehavior",
      "", "", "", "", "", "", "", "", "",
      "",
      "SubelementIdentifier",
      "",
      "ExpressibleByUnicodeScalarLiteral",
      "", "", "", "",
      "NSObjectProtocol",
      "UnsafeMutableRawPointer",
      "", "", "", "",
      "UnpublishingHandler",
      "", "",
      "NSURLErrorCannotDecodeRawData",
      "",
      "ReferenceConvertible",
      "", "", "", "", "", "", "", "",
      "NSCloudSharingErrorMaximum",
      "", "", "", "", "", "", "",
      "NSMapTableCopyIn",
      "", "", "",
      "NSMetadataItemExecutablePlatformKey",
      "", "", "", "", "", "", "", "", "",
      "NSUserActivityConnectionUnavailableError",
      "", "", "", "",
      "NSMetadataItemThemeKey",
      "", "", "",
      "URLUbiquitousItemDownloadingStatus",
      "", "", "",
      "CustomReflectable",
      "TimerPublisher",
      "NSMetadataItemTitleKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "URLSessionUploadTask",
      "", "", "", "", "",
      "LazyDropWhileSequence",
      "", "", "", "", "", "",
      "NSMetadataItemContentTypeKey",
      "", "", "", "", "", "",
      "KeyedDecodingContainerProtocol",
      "", "", "", "", "", "", "",
      "RecoverableError",
      "", "", "", "",
      "NSUTF16LittleEndianStringEncoding",
      "", "", "", "", "", "", "", "", "",
      "NSUTF32LittleEndianStringEncoding",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "AnyIndex",
      "", "", "", "", "", "", "", "", "",
      "HTTPCookieStorage",
      "", "", "", "", "",
      "Behavior",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSNonRetainedObjectHashCallBacks",
      "", "", "", "", "", "", "",
      "NSFileManagerUnmountUnknownError",
      "",
      "NSObjectMapValueCallBacks",
      "", "", "", "", "",
      "NSUserActivityErrorMaximum",
      "", "", "", "", "", "", "", "", "",
      "",
      "DrawingOptions",
      "", "", "", "", "", "", "", "", "",
      "NSNonOwnedPointerMapValueCallBacks",
      "NSMetadataItemContentTypeTreeKey",
      "", "", "",
      "XMLDTD",
      "",
      "SocketNativeHandle",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "ExpressibleByNilLiteral",
      "", "", "", "", "", "", "", "", "",
      "URLSessionStreamTask",
      "", "", "", "",
      "XMLDTDNode",
      "", "",
      "ExpressibleByStringLiteral",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "HTTPCookiePropertyKey",
      "", "", "",
      "DocumentAttributeKey",
      "", "", "", "", "",
      "ValueTransformer",
      "", "", "", "", "", "", "", "",
      "NSMetadataItemAppleLoopsLoopModeKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "NSScriptObjectSpecifier",
      "NSValueTransformerName",
      "", "", "", "",
      "NSWhoseSpecifier",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "NSMetadataItemGenreKey",
      "", "", "", "", "", "", "", "", "",
      "NSExecutableErrorMaximum",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "NSShiftJISStringEncoding",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "LazyFilterSequence",
      "PrefixSequence",
      "NSPOSIXErrorDomain",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "NSMetadataQueryIndexedNetworkScope",
      "NSURLErrorAppTransportSecurityRequiresSecureConnection",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "NSMetadataItemTempoKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "NSFoundationVersionNumber",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSOSF1OperatingSystem",
      "", "", "", "",
      "NSKeyValueValidationError",
      "NSSymbolStringEncoding",
      "", "", "", "", "", "", "",
      "CustomDebugStringConvertible",
      "", "", "", "",
      "NSMetadataItemTextContentKey",
      "CodingUserInfoKey",
      "", "", "", "", "", "", "",
      "NSOwnedPointerMapKeyCallBacks",
      "", "", "", "", "",
      "ExtendedGraphemeClusterType",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "ExtendedGraphemeClusterLiteralType",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "NSAppleEventManager",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "URLUbiquitousSharedItemRole",
      "",
      "URLUbiquitousSharedItemPermissions",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "NSMetadataItemAudioTrackNumberKey",
      "NSUbiquitousFileNotUploadedDueToQuotaError",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "SuspensionBehavior",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "NSSunOSOperatingSystem",
      "", "", "",
      "NSOrthography",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "ExpressibleByDictionaryLiteral",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "BackgroundTaskCancelledReason",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSMetadataQueryUbiquitousDocumentsScope",
      "", "", "", "",
      "NSExecutableArchitectureMismatchError",
      "", "", "", "", "", "", "",
      "UnsafeRawBufferPointer",
      "", "", "", "",
      "NSUbiquitousFileUbiquityServerNotAvailable",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "NSURLProtectionSpaceHTTP",
      "NSURLProtectionSpaceHTTPS",
      "", "", "", "", "", "", "", "",
      "NSURLProtectionSpaceHTTPProxy",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "BlockOperation",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "URLSessionDownloadTask",
      "", "", "", "", "", "", "", "",
      "LazyPrefixWhileCollection",
      "", "", "", "", "", "",
      "NSURLErrorFailingURLErrorKey",
      "", "", "", "", "", "", "",
      "NSOpenStepUnicodeReservedBase",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "NSUbiquitousFileErrorMaximum",
      "",
      "NSURLErrorBadServerResponse",
      "", "", "", "", "", "", "",
      "NSUbiquitousFileErrorMinimum",
      "", "", "", "", "", "", "", "",
      "NSDistributedLock",
      "", "", "", "", "", "", "", "",
      "NSUserActivityHandoffUserInfoTooLargeError",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "NSNEXTSTEPStringEncoding",
      "", "",
      "NSExtensionItemAttributedTitleKey",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "TextLayoutSectionKey",
      "",
      "NSBundleOnDemandResourceInvalidTagError",
      "", "", "", "",
      "NSWindowsNTOperatingSystem",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "NSUserActivityTypeBrowsingWeb",
      "", "",
      "NSTypeIdentifierPhoneNumberText",
      "",
      "NSMapTableStrongMemory",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "AnyHashable",
      "", "",
      "NSMetadataQueryUbiquitousDataScope",
      "", "", "", "", "", "",
      "NetworkServiceType",
      "", "", "", "",
      "AdditiveArithmetic",
      "LazyPrefixWhileSequence",
      "",
      "NSDecimalNumberBehaviors",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "StreamSOCKSProxyVersion",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "NSKeyValueChangeKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "AuthChallengeDisposition",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "AnyKeyPath",
      "NSBundleOnDemandResourceOutOfSpaceError",
      "", "", "",
      "NSURLProtectionSpaceHTTPSProxy",
      "", "", "",
      "NSKeyValueSetMutationKind",
      "NSArchiver",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "NSUTF16BigEndianStringEncoding",
      "", "", "", "", "", "", "", "", "",
      "NSUTF32BigEndianStringEncoding",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "SearchPathDomainMask",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "TextOutputStream",
      "", "", "", "", "", "", "", "",
      "TextOutputStreamable",
      "NSUbiquitousKeyValueStore",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "ActivationType",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "MultipathServiceType",
      "", "", "", "", "", "",
      "NSUbiquitousKeyValueStoreChangeReasonKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "NSUserActivityHandoffFailedError",
      "", "", "",
      "ReferenceWritableKeyPath",
      "",
      "NSKeyValueOperator",
      "", "", "", "", "", "", "",
      "NSKeyValueObservation",
      "", "", "", "", "", "",
      "NSURLErrorNetworkUnavailableReasonKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "NSDebugDescriptionErrorKey",
      "", "", "", "", "", "",
      "NSURLErrorHTTPTooManyRedirects",
      "", "", "", "", "",
      "NSKeySpecifierEvaluationScriptError",
      "", "", "", "", "", "", "",
      "StreamNetworkServiceTypeValue",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "NSKeyValueObservingCustomization",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "NSURLErrorServerCertificateHasUnknownRoot",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "NSMetadataItemGPSTrackKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "NSURLErrorDownloadDecodingFailedToComplete",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "NSUbiquitousKeyValueStoreInitialSyncChange",
      "", "", "", "", "", "", "",
      "NSAppleEventDescriptor",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSIntegerMapKeyCallBacks",
      "", "",
      "HTTPCookieStringPolicy",
      "", "", "", "", "", "", "", "",
      "NSMapTableOptions",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "BookmarkResolutionOptions",
      "", "", "", "", "", "",
      "NSMapTableWeakMemory",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "NSCloudSharingOtherError",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "NSKeyedUnarchiver",
      "", "", "", "", "", "", "",
      "NSURLErrorFileDoesNotExist",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "NSUbiquitousFileUnavailableError",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "NSURLErrorDNSLookupFailed",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "NSURLAuthenticationMethodNTLM",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "NSURLAuthenticationMethodNegotiate",
      "", "", "", "", "", "",
      "NS_UnknownByteOrder",
      "", "", "", "", "", "", "", "", "",
      "",
      "NSURLAuthenticationMethodClientCertificate",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "NSKeyedUnarchiverDelegate",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "NSNonRetainedObjectMapKeyCallBacks",
      "NSObjectMapKeyCallBacks",
      "", "", "", "",
      "NSUbiquitousKeyValueStoreQuotaViolationChange",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "UnsafeMutableBufferPointer",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "NSURLAuthenticationMethodServerTrust",
      "", "", "", "", "", "", "", "", "",
      "StreamSOCKSProxyConfiguration",
      "", "", "", "", "",
      "NSExtensionItemsAndErrorsKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "NSMapTableObjectPointerPersonality",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "NSURLAuthenticationMethodHTTPDigest",
      "", "", "", "", "", "", "", "",
      "URLSessionWebSocketDelegate",
      "", "", "", "",
      "NSURLAuthenticationMethodHTTPBasic",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "NSMetadataItemAlbumKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "QualityOfService",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "ActivityOptions",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "NSBundleOnDemandResourceExceededMaximumSizeError",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "NSURLErrorDataLengthExceedsMaximum",
      "NSMapTableKeyCallBacks",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "WritableKeyPath",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "BookmarkFileCreationOptions",
      "", "", "",
      "NSURLErrorFileOutsideSafeArea",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "NSOwnedPointerHashCallBacks",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "NSURLAuthenticationMethodHTMLForm",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "TextEffectStyle",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "AnyObject",
      "NSTextCheckingResult",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSUbiquitousKeyValueStoreChangedKeysKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "NSMetadataItemFlashOnOffKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "NSURLAuthenticationMethodDefault",
      "", "", "", "", "", "", "",
      "BookmarkCreationOptions",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "UnsafeMutableRawBufferPointer",
      "", "", "", "", "", "", "", "", "",
      "",
      "NSUbiquitousKeyValueStoreServerChange",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSKeyValueObservedChange",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "NSUbiquitousKeyValueStoreAccountChange",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "NSObjectHashCallBacks",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "NSTypeIdentifierDateText",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "NSKeyValueObservingOptions",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSAffineTransform",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "NSKeyedArchiver",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSAffineTransformStruct",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "NSKeyedArchiverDelegate",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "ObservableObject",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "NSTypeIdentifierAddressText",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "NSMapTableValueCallBacks",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "NSTypeIdentifierTransitInformationText",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "NSTextCheckingTypes",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "DataTaskPublisher",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSTextCheckingAllTypes",
      "", "", "", "", "", "", "", "",
      "NSAppleEventTimeOutNone",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "URLSessionWebSocketTask",
      "", "", "", "", "", "", "",
      "URLThumbnailDictionaryItem",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "ExpressibleByExtendedGraphemeClusterLiteral",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "NSTextCheckingAllSystemTypes",
      "", "", "", "",
      "NSTextCheckingAllCustomTypes",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "NSTextCheckingKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "NSOwnedObjectIdentityHashCallBacks",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "NSBackgroundActivityScheduler",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "NSKeyedArchiveRootObjectKey",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "NSAppleEventTimeOutDefault"
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register unsigned int key = hash (str, len);

      if (key <= MAX_HASH_VALUE)
        {
          register const char *s = wordlist[key];

          if (*str == *s && !strncmp (str + 1, s + 1, len - 1) && s[len] == '\0')
            return s;
        }
    }
  return 0;
}
