/* ANSI-C code produced by gperf version 3.1 */
/* Command-line: gperf llamafile/is_keyword_cobol.gperf  */
/* Computed positions: -k'1-3,6-7,12,$' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gperf@gnu.org>."
#endif

#line 1 "llamafile/is_keyword_cobol.gperf"

#include <string.h>
#include <libc/str/tab.h>
#define GPERF_DOWNCASE

#define TOTAL_KEYWORDS 418
#define MIN_WORD_LENGTH 2
#define MAX_WORD_LENGTH 19
#define MIN_HASH_VALUE 27
#define MAX_HASH_VALUE 1817
/* maximum key range = 1791, duplicates = 0 */

#ifndef GPERF_DOWNCASE
#define GPERF_DOWNCASE 1
static unsigned char gperf_downcase[256] =
  {
      0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
     15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
     30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,
     45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
     60,  61,  62,  63,  64,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106,
    107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
    122,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
    105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
    120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
    135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
    150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
    165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
    180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
    195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209,
    210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224,
    225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239,
    240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
    255
  };
#endif

#ifndef GPERF_CASE_STRNCMP
#define GPERF_CASE_STRNCMP 1
static int
gperf_case_strncmp (register const char *s1, register const char *s2, register size_t n)
{
  for (; n > 0;)
    {
      unsigned char c1 = gperf_downcase[(unsigned char)*s1++];
      unsigned char c2 = gperf_downcase[(unsigned char)*s2++];
      if (c1 != 0 && c1 == c2)
        {
          n--;
          continue;
        }
      return (int)c1 - (int)c2;
    }
  return 0;
}
#endif

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash (register const char *str, register size_t len)
{
  static const unsigned short asso_values[] =
    {
      1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818,    0, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818,  423, 1818, 1818, 1818,    0,
        30,   15,   35,   10, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818,   50,  455,  105,   15,    5,
       443,  245,  191,  130,    0,    0,   70,  395,    5,  155,
       335,  230,   20,    0,   15,  295,  438,  165,   25,  508,
        70, 1818, 1818, 1818, 1818,    5, 1818,   50,  455,  105,
        15,    5,  443,  245,  191,  130,    0,    0,   70,  395,
         5,  155,  335,  230,   20,    0,   15,  295,  438,  165,
        25,  508,   70, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818, 1818,
      1818, 1818, 1818, 1818, 1818, 1818
    };
  register unsigned int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[11]];
      /*FALLTHROUGH*/
      case 11:
      case 10:
      case 9:
      case 8:
      case 7:
        hval += asso_values[(unsigned char)str[6]];
      /*FALLTHROUGH*/
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      /*FALLTHROUGH*/
      case 5:
      case 4:
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      /*FALLTHROUGH*/
      case 2:
        hval += asso_values[(unsigned char)str[1]];
      /*FALLTHROUGH*/
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

const char *
is_keyword_cobol (register const char *str, register size_t len)
{
  static const char * const wordlist[] =
    {
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "DE",
      "",
      "SEND",
      "EJECT",
      "",
      "SD",
      "", "", "", "", "",
      "SET",
      "TEST",
      "", "",
      "RENAMES",
      "END",
      "",
      "RESET",
      "", "", "", "",
      "ENTER",
      "",
      "RD",
      "",
      "NEXT",
      "RERUN",
      "RETURN",
      "", "", "",
      "END-RETURN",
      "", "", "",
      "TEXT",
      "",
      "ASSIGN",
      "", "", "",
      "ERROR",
      "STATUS",
      "", "", "", "",
      "ENABLE",
      "END-ADD",
      "",
      "LESS",
      "AREAS",
      "EXTEND",
      "AT",
      "ARE",
      "ELSE",
      "START",
      "NATIVE",
      "ADDRESS",
      "AND",
      "", "",
      "DESTINATION",
      "", "",
      "READ",
      "TRACE",
      "", "",
      "ADD",
      "",
      "ZEROS",
      "ZEROES",
      "",
      "END-READ",
      "REEL",
      "",
      "DELETE",
      "", "",
      "TERMINATE",
      "",
      "SELECT",
      "RELEASE",
      "",
      "END-START",
      "END-DELETE",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "AREA",
      "",
      "RELOAD",
      "IS",
      "SENTENCE",
      "DATA",
      "SKIP1",
      "",
      "CD",
      "",
      "LAST",
      "", "",
      "IN",
      "", "",
      "STANDARD-1",
      "",
      "SERVICE",
      "", "",
      "SKIP3",
      "END-RECEIVE",
      "RECORDS",
      "", "", "", "", "",
      "STANDARD",
      "",
      "ALTER",
      "",
      "ID",
      "", "",
      "SKIP2",
      "RECORD",
      "ON",
      "", "",
      "TITLE",
      "INSERT",
      "",
      "TERMINAL",
      "",
      "STANDARD-2",
      "", "",
      "EXTERNAL",
      "EXIT",
      "INDEX",
      "DETAIL",
      "", "",
      "REDEFINES",
      "", "", "", "",
      "END-WRITE",
      "KANJI",
      "",
      "INDEXED",
      "NOT",
      "SORT",
      "", "",
      "OR",
      "", "", "", "", "", "",
      "ALTERNATE",
      "", "",
      "DECLARATIVES",
      "",
      "SIZE",
      "LINES",
      "END-REWRITE",
      "", "",
      "LINE",
      "ORDER",
      "SORT-RETURN",
      "", "", "",
      "THEN",
      "LINAGE",
      "REWRITE",
      "END-CALL",
      "", "",
      "REWIND",
      "",
      "INDICATE",
      "",
      "CLASS",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "ZERO",
      "", "", "", "",
      "DELIMITED",
      "", "", "",
      "ALL",
      "DELIMITER",
      "THAN",
      "ACCESS",
      "",
      "ESI",
      "", "", "", "", "",
      "RECURSIVE",
      "", "",
      "INSPECT",
      "DECIMAL-POINT",
      "ALSO",
      "",
      "END-SEARCH",
      "SECTION",
      "",
      "CODE",
      "", "",
      "DATE-WRITTEN",
      "", "", "", "",
      "SEGMENT",
      "",
      "EXCEPTION",
      "DESCENDING",
      "ACCEPT",
      "INSTALLATION",
      "",
      "CALL",
      "", "", "",
      "CODE-SET",
      "CORR",
      "",
      "CANCEL",
      "CONTENT",
      "USE",
      "INTO",
      "", "", "", "",
      "JUST",
      "END-STRING",
      "",
      "NO",
      "", "", "", "",
      "GREATER",
      "", "",
      "WRITE",
      "",
      "TO",
      "RUN",
      "", "", "", "",
      "GENERATE",
      "LOCK",
      "SEQUENTIAL",
      "", "", "",
      "TRUE",
      "CLOSE",
      "", "",
      "INITIATE",
      "DOWN",
      "WORDS",
      "COLUMN",
      "", "", "", "", "", "", "", "",
      "USAGE",
      "", "",
      "SEQUENCE",
      "EGCS",
      "", "", "", "", "", "", "", "", "",
      "",
      "WHEN",
      "OCCURS",
      "",
      "DATE-COMPILED",
      "",
      "NULLS",
      "", "", "", "", "", "",
      "REPORTS",
      "",
      "SIGN",
      "",
      "OTHER",
      "", "", "",
      "UNTIL",
      "SPACES",
      "", "", "",
      "SPACE",
      "REPORT",
      "", "", "",
      "INITIALIZE",
      "", "", "",
      "RH",
      "",
      "AUTHOR",
      "",
      "CONTAINS",
      "TAPE",
      "", "", "", "", "",
      "RIGHT",
      "", "",
      "SEPARATE",
      "", "", "", "", "", "", "", "",
      "REMARKS",
      "SEGMENT-LIMIT",
      "RETURNING",
      "MERGE",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "SEARCH",
      "NULL",
      "", "", "", "",
      "UNIT",
      "",
      "METHOD",
      "", "",
      "SAME",
      "",
      "END-PERFORM",
      "", "", "", "", "",
      "INITIAL",
      "", "", "",
      "SOURCE",
      "LINKAGE",
      "LENGTH",
      "REMAINDER",
      "", "", "",
      "TRAILING",
      "",
      "FD",
      "CHARACTERS",
      "",
      "SPECIAL-NAMES",
      "INHERITS",
      "RESERVE",
      "",
      "REPLACE",
      "END-INVOKE",
      "RETURN-CODE",
      "", "", "",
      "REFERENCES",
      "CH",
      "INPUT",
      "REVERSED",
      "REFERENCE",
      "", "",
      "CHARACTER",
      "", "",
      "CONTROLS",
      "", "",
      "OUTPUT",
      "", "",
      "OPEN",
      "WITH",
      "", "", "",
      "STOP",
      "BASIS",
      "",
      "ROUNDED",
      "EGI",
      "", "", "",
      "LINE-COUNTER",
      "", "",
      "LOW-VALUES",
      "ENDING",
      "SELF",
      "TALLYING",
      "LOW-VALUE",
      "THRU",
      "", "", "",
      "RECORDING",
      "TABLE",
      "STRING",
      "END-UNSTRING",
      "AFTER",
      "",
      "END-EVALUATE",
      "",
      "LEFT",
      "ENTRY",
      "",
      "QUEUE",
      "", "", "",
      "METACLASS",
      "TIMES",
      "", "", "",
      "TIME",
      "", "",
      "PROCEED",
      "",
      "ASCENDING",
      "CONVERTING",
      "",
      "GO",
      "", "", "", "", "", "",
      "VALUES",
      "", "",
      "CONTROL",
      "VALUE",
      "", "",
      "EVALUATE",
      "",
      "FALSE",
      "MODE",
      "COUNT",
      "",
      "MODULES",
      "CONTINUE",
      "DBCS",
      "BLANK",
      "", "",
      "PASSWORD",
      "SORT-CORE-SIZE",
      "RECEIVE",
      "",
      "SORT-CONTROL",
      "READY",
      "INVOKE",
      "SORT-MERGE",
      "END-COMPUTE",
      "", "", "", "", "",
      "SORT-MESSAGE",
      "",
      "DIVIDE",
      "",
      "LIMITS",
      "", "", "",
      "EQUAL",
      "",
      "PICTURE",
      "END-DIVIDE",
      "", "", "", "",
      "FIRST",
      "",
      "LIMIT",
      "GLOBAL",
      "REMOVAL",
      "", "", "",
      "NATIVE_BINARY",
      "SYNC",
      "", "", "", "",
      "LEADING",
      "", "",
      "WORKING-STORAGE",
      "", "", "",
      "ENVIRONMENT",
      "", "", "",
      "OPTIONAL",
      "PAGE",
      "",
      "FOR",
      "ORGANIZATION",
      "SUPPRESS",
      "", "",
      "OBJECT",
      "",
      "TALLY",
      "",
      "LABEL",
      "",
      "FILE",
      "FINAL",
      "WHEN-COMPILED",
      "SUPER",
      "", "", "", "",
      "PURGE",
      "COMP-1",
      "MESSAGE",
      "EMI",
      "", "", "", "", "", "", "",
      "COMMON",
      "POINTER",
      "", "",
      "USING",
      "RELATIVE",
      "",
      "PIC",
      "", "",
      "COMP-5",
      "LINAGE-COUNTER",
      "", "",
      "BLOCK",
      "QUOTES",
      "COMPUTE",
      "UNSTRING",
      "FILLER",
      "QUOTE",
      "COMP-3",
      "", "", "", "", "", "", "", "", "",
      "MORE-LABELS",
      "",
      "CBL",
      "PLUS",
      "", "", "", "", "",
      "COMMA",
      "",
      "DISPLAY-1",
      "", "", "", "", "", "",
      "PH",
      "",
      "COMP-2",
      "OMITTED",
      "", "", "", "", "", "",
      "COLLATING",
      "SYNCHRONIZED",
      "COMP-4",
      "", "", "", "", "", "", "", "",
      "INVALID",
      "NUMBER",
      "", "", "", "", "", "",
      "HEADING",
      "", "", "", "", "",
      "DEPENDING",
      "",
      "OVERRIDE",
      "", "",
      "REPORTING",
      "GROUP",
      "", "", "", "",
      "PROCESSING",
      "", "", "", "", "",
      "SECURITY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "COMPUTATIONAL-1",
      "", "",
      "POSITION",
      "",
      "COBOL",
      "", "", "",
      "UPON",
      "COMPUTATIONAL-5",
      "", "", "", "",
      "COMPUTATIONAL-3",
      "CLASS-ID",
      "", "", "", "", "", "", "", "",
      "DUPLICATES",
      "", "", "", "",
      "COMPUTATIONAL-2",
      "",
      "END-SUBTRACT",
      "", "",
      "COMPUTATIONAL-4",
      "", "", "", "", "", "", "", "", "",
      "PROCEDURES",
      "", "",
      "EOP",
      "PROCEDURE",
      "",
      "NEGATIVE",
      "", "", "", "", "", "",
      "TOP",
      "", "", "", "", "",
      "REPLACING",
      "", "", "",
      "COMPUTATIONAL",
      "", "", "", "", "", "",
      "THROUGH",
      "GOBACK",
      "", "", "", "",
      "I-O",
      "TYPE",
      "", "", "",
      "RANDOM",
      "IDENTIFICATION",
      "PRINTING",
      "SORT-MODE-SIZE",
      "DYNAMIC",
      "",
      "METHOD-ID",
      "CORRESPONDING",
      "JUSTIFIED\011 ",
      "",
      "DIVISION",
      "", "", "", "", "",
      "SHIFT-IN",
      "", "", "", "", "", "",
      "ALPHANUMERIC-EDITED",
      "", "",
      "SORT-FILE-SIZE",
      "", "", "", "",
      "PADDING",
      "", "", "", "",
      "END-OF-PAGE",
      "RF",
      "DEBUG-SUB-1",
      "", "", "", "", "", "", "",
      "END-IF",
      "DEBUG-NAME",
      "BEFORE",
      "", "", "",
      "SHIFT-OUT",
      "DEBUG-SUB-3",
      "", "", "",
      "SUBTRACT",
      "", "", "", "", "", "", "", "", "",
      "ALPHABET",
      "DEBUG-SUB-2",
      "", "",
      "PAGE-COUNTER",
      "", "", "", "", "", "",
      "I-O-CONTROL",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "EVERY",
      "",
      "COMMUNICATION",
      "", "", "",
      "UP",
      "", "", "", "", "", "",
      "NUMERIC-EDITED",
      "", "",
      "ALPHANUMERIC",
      "CONFIGURATION",
      "",
      "PROGRAM-ID",
      "", "",
      "DEBUG-LINE",
      "", "", "", "", "", "", "", "",
      "ADVANCING",
      "CF",
      "COMP",
      "",
      "OVERFLOW",
      "MOVE",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "VARYING",
      "",
      "PROCEDURE-POINTER",
      "", "", "",
      "LOCAL-STORAGE",
      "FROM",
      "IF",
      "", "",
      "ALPHABETIC-LOWER",
      "DEBUG-CONTENTS",
      "REPOSITORY",
      "KEY",
      "", "", "", "", "",
      "ALPHABETIC",
      "", "", "", "", "", "", "", "", "",
      "",
      "FUNCTION",
      "NUMERIC",
      "OF",
      "", "",
      "CURRENCY",
      "", "", "", "", "", "", "", "",
      "FILE-CONTROL",
      "", "", "",
      "CLOCK-UNITS",
      "",
      "SUB-QUEUE-1",
      "", "", "",
      "HIGH-VALUES",
      "", "", "",
      "HIGH-VALUE",
      "",
      "POSITIVE",
      "", "",
      "ANY",
      "",
      "SUB-QUEUE-3",
      "", "", "", "", "", "", "",
      "DAY",
      "", "", "",
      "SUM",
      "",
      "INPUT-OUTPUT",
      "SUB-QUEUE-2",
      "", "",
      "BEGINNING",
      "", "", "", "", "", "", "", "", "",
      "DEBUGGING",
      "", "",
      "COPY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "COM-REG",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "PERFORM",
      "MULTIPLE",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "SOURCE-COMPUTER",
      "", "", "", "", "", "", "",
      "SYMBOLIC",
      "",
      "DISPLAY",
      "", "", "", "",
      "PF",
      "", "", "", "", "", "", "", "", "",
      "APPLY",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "ALPHABETIC-UPPER",
      "", "", "", "", "", "", "", "",
      "FOOTING",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "GIVING",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "PROGRAM",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "OBJECT-COMPUTER",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "PACKED-DECIMAL",
      "", "", "",
      "WRITE-ONLY",
      "", "", "", "", "", "",
      "END-MULTIPLY",
      "", "",
      "BOTTOM",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "DEBUG-ITEM",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "DAY-OF-WEEK",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "BY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "OFF",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "BINARY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "MULTIPLY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "MEMORY"
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register unsigned int key = hash (str, len);

      if (key <= MAX_HASH_VALUE)
        {
          register const char *s = wordlist[key];

          if ((((unsigned char)*str ^ (unsigned char)*s) & ~32) == 0 && !gperf_case_strncmp (str, s, len) && s[len] == '\0')
            return s;
        }
    }
  return 0;
}
