/* ANSI-C code produced by gperf version 3.1 */
/* Command-line: gperf is_keyword_sql.gperf  */
/* Computed positions: -k'1-4,6-7,9,12,$' */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gperf@gnu.org>."
#endif

#line 1 "is_keyword_sql.gperf"

#include <string.h>
#include <libc/str/tab.h>
#define GPERF_DOWNCASE

#define TOTAL_KEYWORDS 927
#define MIN_WORD_LENGTH 2
#define MAX_WORD_LENGTH 32
#define MIN_HASH_VALUE 17
#define MAX_HASH_VALUE 7452
/* maximum key range = 7436, duplicates = 0 */

#ifndef GPERF_DOWNCASE
#define GPERF_DOWNCASE 1
static unsigned char gperf_downcase[256] =
  {
      0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
     15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,
     30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,
     45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
     60,  61,  62,  63,  64,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106,
    107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
    122,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
    105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
    120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
    135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149,
    150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
    165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
    180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
    195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209,
    210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224,
    225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239,
    240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
    255
  };
#endif

#ifndef GPERF_CASE_STRNCMP
#define GPERF_CASE_STRNCMP 1
static int
gperf_case_strncmp (register const char *s1, register const char *s2, register size_t n)
{
  for (; n > 0;)
    {
      unsigned char c1 = gperf_downcase[(unsigned char)*s1++];
      unsigned char c2 = gperf_downcase[(unsigned char)*s2++];
      if (c1 != 0 && c1 == c2)
        {
          n--;
          continue;
        }
      return (int)c1 - (int)c2;
    }
  return 0;
}
#endif

#ifdef __GNUC__
__inline
#else
#ifdef __cplusplus
inline
#endif
#endif
static unsigned int
hash (register const char *str, register size_t len)
{
  static const unsigned short asso_values[] =
    {
      7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453,    0, 7453, 7453,    0,   25,
         0,   20,   10, 7453, 7453, 7453,    5, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453,  175, 1604,  430,   50,    0,
       970,  600, 1909,  255, 1349, 1941,  330,  780,   15,   15,
       890, 1849,   65,   10,    5,   70, 1671, 1693, 1264, 1714,
       235,    5, 7453, 7453, 7453,  450, 7453,  175, 1604,  430,
        50,    0,  970,  600, 1909,  255, 1349, 1941,  330,  780,
        15,   15,  890, 1849,   65,   10,    5,   70, 1671, 1693,
      1264, 1714,  235,    5, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453, 7453,
      7453, 7453, 7453, 7453, 7453, 7453, 7453
    };
  register unsigned int hval = len;

  switch (hval)
    {
      default:
        hval += asso_values[(unsigned char)str[11]];
      /*FALLTHROUGH*/
      case 11:
      case 10:
      case 9:
        hval += asso_values[(unsigned char)str[8]];
      /*FALLTHROUGH*/
      case 8:
      case 7:
        hval += asso_values[(unsigned char)str[6]];
      /*FALLTHROUGH*/
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      /*FALLTHROUGH*/
      case 5:
      case 4:
        hval += asso_values[(unsigned char)str[3]];
      /*FALLTHROUGH*/
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      /*FALLTHROUGH*/
      case 2:
        hval += asso_values[(unsigned char)str[1]];
      /*FALLTHROUGH*/
      case 1:
        hval += asso_values[(unsigned char)str[0]+1];
        break;
    }
  return hval + asso_values[(unsigned char)str[len - 1]];
}

const char *
is_keyword_sql (register const char *str, register size_t len)
{
  static const char * const wordlist[] =
    {
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "NE",
      "SET",
      "", "", "", "",
      "RET",
      "", "", "",
      "SS",
      "", "", "", "",
      "DO",
      "",
      "SETS",
      "", "", "", "",
      "ZONE",
      "", "", "",
      "NOT",
      "", "", "",
      "NO",
      "",
      "NONE",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "CT",
      "", "", "", "", "", "", "", "", "",
      "CS",
      "", "", "",
      "MONTHS",
      "SESSION",
      "", "", "", "", "", "",
      "MODE",
      "", "", "",
      "COS",
      "", "", "", "", "", "", "",
      "RESUME",
      "RESTORE",
      "", "", "", "",
      "TO",
      "", "", "",
      "RESULT",
      "RESTART",
      "", "", "", "", "",
      "RUN",
      "",
      "MONSESSION",
      "STORES",
      "CONTENT",
      "", "", "",
      "RETURN",
      "ROUTINE",
      "", "", "", "",
      "RETURNS",
      "", "", "", "", "",
      "MOD",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "CD",
      "", "",
      "CROSS",
      "MODULE",
      "", "", "",
      "COUNT",
      "SOURCE",
      "", "", "",
      "SETRESRATE",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "CONTINUE",
      "", "", "", "", "",
      "DATE",
      "", "", "", "", "", "", "", "", "",
      "",
      "STATE",
      "STORED",
      "", "", "", "", "", "", "", "", "",
      "RENAME",
      "", "",
      "TRUE",
      "",
      "MONRESOURCE",
      "", "", "", "", "",
      "SETUSER",
      "", "", "", "", "", "", "", "",
      "SETSESSRATE",
      "", "",
      "STRUCTURE",
      "", "", "", "", "", "", "", "", "",
      "CASE",
      "", "", "", "", "", "", "", "", "",
      "CAST",
      "READS",
      "",
      "QUERYNO",
      "", "", "", "", "", "", "",
      "START",
      "", "", "",
      "CORR",
      "", "",
      "SESSION_USER",
      "", "", "",
      "CASE_N",
      "", "", "", "", "", "",
      "TAN",
      "", "",
      "DSSIZE",
      "CURRENT",
      "", "", "", "",
      "CURRENT_TIME",
      "",
      "READ",
      "",
      "CURRENT_TIMEZONE",
      "",
      "SIN",
      "HOST",
      "",
      "CREATE",
      "", "",
      "SENSITIVE",
      "", "", "",
      "MIN",
      "", "",
      "CONSTRUCTOR",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "TREAT",
      "",
      "CURRENT_TRANSFORM_GROUP_FOR_TYPE",
      "", "", "", "", "", "", "", "",
      "CURSOR",
      "CURRENT_DATE",
      "", "", "",
      "DELETE",
      "", "", "", "", "", "", "",
      "TRAN",
      "", "",
      "CURRENT_ROLE",
      "", "", "",
      "SELECT",
      "", "", "", "", "",
      "RELEASE",
      "",
      "ROLE",
      "CONSTRAINT",
      "MINUTE",
      "", "", "", "",
      "CONSTRAINTS",
      "", "", "",
      "MINUS",
      "", "",
      "CONTAINS",
      "", "", "", "", "", "", "", "",
      "MINUTES",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "TRUNCATE",
      "",
      "CLOSE",
      "", "", "",
      "RULE",
      "CLONE",
      "", "", "", "",
      "HOURS",
      "", "", "", "", "", "", "", "",
      "CONDITION",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "BT",
      "MULTISET",
      "", "", "", "", "", "", "", "",
      "MONITOR",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "CURRENT_SCHEMA",
      "", "", "", "",
      "HOUR",
      "", "", "", "", "", "", "",
      "CURRENT_USER",
      "", "", "", "", "", "", "",
      "YEARS",
      "HOUR_SECOND",
      "SECTION",
      "", "", "", "", "",
      "STANDARD",
      "SIZE",
      "",
      "COLUMN",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "BUT",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "CONCAT",
      "SECONDS",
      "", "", "", "",
      "RADIANS",
      "",
      "DATA",
      "", "", "",
      "RESOURCE",
      "", "", "",
      "CONNECT",
      "DOCUMENT",
      "YEAR",
      "", "",
      "NOAUDIT",
      "DATABASE",
      "", "", "", "", "", "", "",
      "SECOND",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "DATABASES",
      "CONNECTION",
      "", "", "", "", "", "", "", "", "",
      "CLASS",
      "", "", "", "", "", "", "", "", "",
      "MLOAD",
      "", "", "", "", "", "",
      "CLUSTER",
      "", "", "", "", "", "", "",
      "DESTRUCTOR",
      "", "",
      "MODIFIES",
      "",
      "NTILE",
      "",
      "DELAYED",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "HANDLER",
      "",
      "CLUSTERED",
      "", "", "", "", "", "", "", "", "",
      "MIDDLEINT",
      "", "", "", "", "", "", "",
      "MATCHES",
      "", "",
      "STATISTICS",
      "", "", "", "", "", "", "",
      "DEL",
      "",
      "TITLE",
      "",
      "NONCLUSTERED",
      "SEL",
      "FREE",
      "",
      "FREEZE",
      "", "", "", "", "", "",
      "SSL",
      "", "", "", "", "", "",
      "MERGE",
      "", "", "", "", "", "",
      "DEGREES",
      "", "", "", "", "",
      "BIT",
      "", "", "", "",
      "CONTAINSTABLE",
      "HOLD",
      "MACRO",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "RAISERROR",
      "", "",
      "CASCADE",
      "RESTRICT",
      "", "", "", "",
      "DISTINCT",
      "", "", "", "", "", "", "", "",
      "COLLATE",
      "", "", "", "", "", "", "",
      "TRACE",
      "",
      "REGR_R2",
      "FOR",
      "", "", "", "",
      "KURTOSIS",
      "",
      "FOUND",
      "", "", "", "",
      "NULLS",
      "", "", "", "", "", "", "", "", "",
      "NESTED_TABLE_ID",
      "", "",
      "CASCADED",
      "", "", "",
      "DISABLE",
      "", "", "", "",
      "LE",
      "",
      "RECURSIVE",
      "", "", "", "", "", "", "",
      "LT",
      "", "", "", "", "", "", "",
      "CCSID",
      "", "",
      "RESIGNAL",
      "SOME",
      "RANGE",
      "", "", "", "", "", "",
      "LN",
      "",
      "LESS",
      "", "", "", "", "", "", "",
      "MICROSECONDS",
      "", "", "", "", "",
      "DISABLED",
      "", "",
      "COLLID",
      "DECLARE",
      "", "", "", "", "", "",
      "TRANSLATE",
      "", "", "", "", "", "", "", "", "",
      "REAL",
      "",
      "MICROSECOND",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "DEC",
      "", "", "", "", "", "", "", "", "",
      "",
      "DESC",
      "", "", "", "", "", "", "", "",
      "MINUTE_SECOND",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "ONE",
      "DUAL",
      "", "", "", "", "", "",
      "REPEAT",
      "",
      "QUANTILE",
      "", "", "",
      "ON",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "FIRST",
      "", "", "", "", "", "", "", "", "",
      "MAINTAINED",
      "", "", "", "", "", "", "",
      "RESULT_SET_LOCATOR",
      "", "", "", "", "",
      "REGR_INTERCEPT",
      "DEALLOCATE",
      "", "", "",
      "CEIL",
      "",
      "FUSION",
      "",
      "OUT",
      "",
      "LEAST",
      "", "",
      "NATIONAL",
      "LAST",
      "", "",
      "ET",
      "", "",
      "NAMES",
      "", "", "",
      "STATEMENT",
      "",
      "CALLED",
      "MATERIALIZED",
      "", "", "", "", "", "", "", "",
      "ROLLFORWARD",
      "BOOLEAN",
      "SUCCEEDS",
      "", "",
      "DOMAIN",
      "",
      "ZEROFILL",
      "", "", "", "", "", "",
      "REFERENCES",
      "", "",
      "COALESCE",
      "", "", "",
      "OR",
      "",
      "COLLATION",
      "NAMED",
      "", "", "", "",
      "FLOOR",
      "", "", "", "",
      "OUTER",
      "MASTER_BIND",
      "", "", "",
      "DEREF",
      "", "", "", "", "",
      "CURRENT_LC_CTYPE",
      "NOTNULL",
      "DATEFORM",
      "", "", "", "", "", "", "",
      "STATIC",
      "", "",
      "LEAD",
      "", "", "", "", "",
      "LINES",
      "", "", "", "", "", "", "", "",
      "LOAD",
      "ORDER",
      "", "", "",
      "NULL",
      "", "", "", "", "", "",
      "LINENO",
      "",
      "END",
      "", "", "",
      "CURRVAL",
      "DEFERRED",
      "", "", "",
      "SUSPEND",
      "", "", "", "", "", "", "", "", "",
      "NATURAL",
      "",
      "TIME",
      "",
      "TRANSLATION",
      "", "",
      "TERMINATE",
      "FORCE",
      "",
      "COLUMN_VALUE",
      "", "",
      "FALSE",
      "", "", "", "", "", "",
      "TRIGGER",
      "STARTING",
      "",
      "FLOAT",
      "", "", "", "", "",
      "FLOAT8",
      "", "", "", "", "", "",
      "MINUTE_MICROSECOND",
      "", "",
      "FLOAT4",
      "", "", "",
      "REGR_COUNT",
      "FENCED",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "TERMINATED",
      "", "", "", "",
      "DISCONNECT",
      "",
      "COLLECT",
      "", "", "", "", "", "",
      "RPAD",
      "",
      "SCROLL",
      "CURRENT_TIMESTAMP",
      "", "",
      "ERROR",
      "LINEAR",
      "", "",
      "FILE",
      "", "",
      "CAPTURE",
      "", "", "", "", "", "", "",
      "COLLECTION",
      "", "", "", "", "", "", "", "", "",
      "",
      "TRANSACTION",
      "",
      "SECURITYAUDIT",
      "", "", "", "", "",
      "CALL",
      "", "", "", "",
      "CUME_DIST",
      "ERASE",
      "", "", "", "", "",
      "DEFINE",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "REPOVERRIDE",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "SPOOL",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "RANGE_N",
      "SECOND_MICROSECOND",
      "", "", "", "",
      "NEXT",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "BEGIN",
      "", "", "", "", "", "", "", "",
      "ELSE",
      "", "",
      "FOREIGN",
      "", "", "", "", "",
      "OLD",
      "", "",
      "FILTER",
      "", "", "", "",
      "DIAGNOSTICS",
      "RUNNING",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "SCOPE",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "SUCCESSFUL",
      "", "", "", "", "",
      "IS",
      "",
      "INT2",
      "MEDIUMINT",
      "", "",
      "INT",
      "", "",
      "FINAL",
      "IN",
      "",
      "INT8",
      "", "", "",
      "INS",
      "",
      "SEPARATOR",
      "INSERT",
      "", "",
      "INT4",
      "", "", "", "",
      "INTERSECT",
      "", "", "", "",
      "INTO",
      "", "",
      "LOCALE",
      "",
      "FUNCTION",
      "STRING_CS",
      "", "", "",
      "INT3",
      "", "",
      "CURRENT_DEFAULT_TRANSFORM_GROUP",
      "", "", "", "",
      "BEFORE",
      "",
      "INT1",
      "",
      "LOG10",
      "INTERSECTION",
      "", "", "",
      "LOGON",
      "ITERATE",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "TRAILING",
      "", "", "", "", "",
      "INNER",
      "", "", "", "", "", "", "", "", "",
      "INOUT",
      "NOCOMPRESS",
      "", "", "", "", "", "", "", "",
      "NORMALIZE",
      "", "", "", "", "", "",
      "FORMAT",
      "", "", "", "", "", "", "",
      "MAXEXTENTS",
      "", "", "", "", "",
      "CURRENT_CATALOG",
      "",
      "DEFAULT",
      "", "", "",
      "ONLINE",
      "",
      "LOCATORS",
      "", "", "", "", "", "",
      "SPACE",
      "INTEGER",
      "",
      "SEMANTICSIMILARITYTABLE",
      "", "", "",
      "READTEXT",
      "", "",
      "SEMANTICSIMILARITYDETAILSTABLE",
      "", "", "", "", "",
      "HOUR_MINUTE",
      "", "", "", "", "",
      "DECIMAL",
      "ROUND_UP",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "BTRIM",
      "SIGNAL",
      "", "", "", "", "", "", "", "",
      "DEFERRABLE",
      "",
      "LOCATOR",
      "", "", "",
      "BIGINT",
      "", "", "", "", "", "", "",
      "RETURNING",
      "", "", "", "", "", "",
      "HOUR_MICROSECOND",
      "",
      "SMALLINT",
      "", "", "", "", "",
      "KILL",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "ESCAPE",
      "", "",
      "WRITE",
      "", "", "", "", "",
      "MATCH_RECOGNIZE",
      "", "",
      "DECFLOAT",
      "", "", "",
      "SIMILAR",
      "STOGROUP",
      "", "", "",
      "CM",
      "WRITETEXT",
      "",
      "TIMEZONE_MINUTE",
      "AT",
      "", "", "",
      "INTEGERDATE",
      "ROUND_FLOOR",
      "", "", "",
      "LARGE",
      "AS",
      "CATALOG",
      "", "", "", "", "", "", "", "", "",
      "",
      "SUM",
      "", "",
      "COMMIT",
      "", "", "", "",
      "ERRORTABLES",
      "", "", "", "", "", "", "", "", "",
      "",
      "COMMENT",
      "",
      "MSUM",
      "",
      "INSTEAD",
      "", "",
      "FULL",
      "", "",
      "REPLACE",
      "",
      "LOCALTIME",
      "", "",
      "ARE",
      "", "",
      "DESCRIPTOR",
      "", "", "", "", "", "", "", "",
      "USE",
      "", "", "", "", "", "", "",
      "ESCAPED",
      "",
      "CSUM",
      "DOUBLE",
      "",
      "REVERT",
      "", "", "", "",
      "REVOKE",
      "", "",
      "SUBSET",
      "", "",
      "WAIT",
      "", "", "", "", "", "", "", "",
      "UNNEST",
      "", "", "", "",
      "AND",
      "", "", "", "", "",
      "CUBE",
      "", "", "", "",
      "TIMEZONE_HOUR",
      "END_FRAME",
      "LOCAL",
      "", "",
      "CORRESPONDING",
      "FREESPACE",
      "ZEROIFNULL",
      "",
      "ROWS",
      "",
      "ROWSET",
      "", "",
      "COMPUTE",
      "", "",
      "DIAGNOSTIC",
      "", "", "", "", "", "",
      "ADD",
      "",
      "RETRIEVE",
      "",
      "RECONFIGURE",
      "",
      "COMPRESS",
      "LEFT",
      "", "", "", "", "",
      "UNDO",
      "", "", "", "", "", "", "", "", "",
      "COMPLETION",
      "", "", "", "", "", "", "", "", "",
      "",
      "SYSDATE",
      "", "", "", "", "", "",
      "EDITPROC",
      "", "", "",
      "LATERAL",
      "",
      "ATAN2",
      "",
      "UNDER",
      "", "", "", "", "",
      "INITIATE",
      "ENCLOSED",
      "OPEN",
      "USER",
      "RANDOM",
      "",
      "ATAN",
      "", "", "",
      "MLINREG",
      "", "",
      "SUBSTR",
      "", "", "", "", "", "", "",
      "CONVERT",
      "", "", "",
      "TEXTSIZE",
      "", "", "",
      "MSUBSTR",
      "",
      "NUMPARTS",
      "", "", "", "", "", "", "",
      "WAITFOR",
      "", "", "",
      "SAVE",
      "SAMPLE",
      "CEILING",
      "", "", "",
      "REFERENCING",
      "XOR",
      "",
      "DROP",
      "CLASSIFIER",
      "", "",
      "TOP",
      "", "",
      "OUTPUT",
      "",
      "ROUND_CEILING",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "LTRIM",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "ASIN",
      "",
      "INSENSITIVE",
      "", "",
      "STEPINFO",
      "",
      "DBINFO",
      "GE",
      "",
      "DAYS",
      "NOWAIT",
      "REGR_SLOPE",
      "",
      "SPATIAL",
      "",
      "QUERY",
      "",
      "GT",
      "GET",
      "ASSERTION",
      "", "", "", "", "", "", "", "", "",
      "SQRT",
      "", "",
      "SIMPLE",
      "", "",
      "OMIT",
      "",
      "GO",
      "FREETEXT",
      "", "", "", "", "", "",
      "LPAD",
      "", "", "",
      "REF",
      "TRIM",
      "",
      "REQUEST",
      "", "", "", "", "", "",
      "GOTO",
      "MONTH",
      "", "", "", "", "", "", "", "",
      "MAP",
      "QUALIFIED",
      "",
      "UNION",
      "", "", "", "", "",
      "PER",
      "", "",
      "IGNORE",
      "PORTION",
      "NUMERIC",
      "INDICATOR",
      "AUDIT",
      "", "", "",
      "DETERMINISTIC",
      "", "", "", "",
      "LOG",
      "",
      "JSON",
      "REQUIRE",
      "",
      "ISOLATION",
      "", "", "", "",
      "READ_WRITE",
      "ALTER",
      "", "",
      "MATCH_NUMBER",
      "THEN",
      "LONG",
      "", "", "", "", "", "", "", "",
      "END_PARTITION",
      "UNSIGNED",
      "", "", "",
      "ROWID",
      "UID",
      "CURRENT_SERVER",
      "", "", "", "",
      "METHOD",
      "", "", "",
      "CURRENT_ROW",
      "NULLIFZERO",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "PREORDER",
      "", "", "", "", "", "",
      "STYLE",
      "", "", "", "",
      "OPENDATASOURCE",
      "", "", "",
      "KEYS",
      "", "", "",
      "ANSIDATE",
      "ACOS",
      "", "",
      "OPTION",
      "",
      "ASSOCIATE",
      "",
      "LIMIT",
      "", "", "",
      "SUBSCRIBER",
      "GROUPS",
      "TINYINT",
      "", "", "", "", "", "", "", "", "",
      "ERRLVL",
      "", "", "", "",
      "INCONSISTENT",
      "",
      "PART",
      "", "", "",
      "STARTUP",
      "",
      "TRANSLATE_REGEX",
      "ISNULL",
      "",
      "ELEMENT",
      "",
      "KEEP",
      "UNDEFINED",
      "REPLICATION",
      "", "", "", "", "", "", "", "", "",
      "NEXTVAL",
      "PAD",
      "", "", "", "", "", "", "",
      "VOLUMES",
      "PATTERN",
      "", "", "",
      "SAVEPOINT",
      "ANALYSE",
      "", "",
      "OPERATION",
      "", "", "", "", "", "", "", "",
      "BYTE",
      "IDENTITY_INSERT",
      "CHANGE",
      "", "",
      "LAG",
      "SHARE",
      "", "", "",
      "SAMPLEID",
      "BYTES",
      "BETWEEN",
      "", "", "", "", "", "",
      "GREATEST",
      "",
      "GRANT",
      "",
      "REVALIDATE",
      "MINIMUM",
      "", "", "",
      "BYTEINT",
      "PASSWORD",
      "",
      "TABLE",
      "", "",
      "ALTERAND",
      "THAN",
      "", "", "", "", "",
      "PRINT",
      "DISTRIBUTED",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "BROWSE",
      "FILLFACTOR",
      "", "",
      "GENERATED",
      "CHARS",
      "", "", "",
      "PSID",
      "",
      "VARIANT",
      "", "", "", "", "", "",
      "LEADING",
      "", "",
      "PADDED",
      "", "", "", "", "", "", "", "", "",
      "",
      "CONVERT_TABLE_HEADER",
      "LOADING",
      "",
      "FROM",
      "JOIN",
      "ROWCOUNT",
      "", "",
      "JAR",
      "", "",
      "CASESPECIFIC",
      "",
      "PRIOR",
      "", "", "", "", "", "", "", "", "",
      "",
      "MDIFF",
      "",
      "ORGANIZATION",
      "CHAR",
      "", "", "",
      "OUTFILE",
      "VALUE",
      "",
      "PERIOD",
      "",
      "FREETEXTTABLE",
      "", "", "",
      "UNTIL",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "VALUES",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "DESCRIBE",
      "ENCODING",
      "", "", "",
      "VCAT",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "ROUND_DOWN",
      "",
      "ACTION",
      "", "", "",
      "INPUT",
      "", "", "", "", "", "", "", "", "",
      "",
      "TRY_CONVERT",
      "", "", "", "", "", "", "",
      "LANGUAGE",
      "PARAMETERS",
      "", "", "", "", "",
      "ERRORFILES",
      "", "", "", "", "",
      "ANALYZE",
      "", "",
      "HELP",
      "", "", "", "",
      "INITIALIZE",
      "",
      "PERCENT",
      "SEQUENCE",
      "",
      "ALIAS",
      "", "",
      "SQLSTATE",
      "",
      "MEDIUMTEXT",
      "", "", "",
      "PLAN",
      "", "", "", "",
      "PARTITION",
      "", "",
      "REGEXP",
      "",
      "INCLUSIVE",
      "NCLOB",
      "", "", "", "", "", "", "", "",
      "PARAMETER",
      "PROTECTION",
      "", "",
      "PRECEDES",
      "", "",
      "ENCRYPTION",
      "", "", "", "", "", "",
      "POSITION",
      "VERSIONING",
      "", "", "", "", "", "",
      "PARTITIONED",
      "", "", "", "",
      "MASTER_SSL_VERIFY_SERVER_CERT",
      "", "", "", "", "", "", "", "", "",
      "IDENTITYCOL",
      "", "", "",
      "RELATIVE",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "USAGE",
      "", "", "", "",
      "INITIAL",
      "ALLOCATE",
      "", "", "",
      "ROLLUP",
      "", "", "", "",
      "ASUTIME",
      "ASC",
      "", "",
      "TBL_CS",
      "", "", "",
      "DISTINCTROW",
      "",
      "DISALLOW",
      "SECURITY",
      "PROCEDURE",
      "",
      "ACCESS",
      "", "", "", "", "",
      "ENDING",
      "DAY_HOUR",
      "", "", "",
      "JSON_TABLE",
      "",
      "EXIT",
      "", "",
      "DENSE_RANK",
      "", "",
      "DICTIONARY",
      "CARDINALITY",
      "ACCOUNT",
      "", "", "",
      "JSON_SERIALIZE",
      "",
      "SQL",
      "", "", "", "", "", "", "",
      "EXISTS",
      "", "", "",
      "CYCLE",
      "", "", "",
      "UC",
      "",
      "MEMBER",
      "", "",
      "OPTIMIZE",
      "MATCH",
      "",
      "RLIKE",
      "", "", "", "",
      "SCHEMAS",
      "", "", "", "", "", "", "", "", "",
      "USING",
      "",
      "LOWER",
      "", "", "", "", "", "", "", "",
      "SPECIFICTYPE",
      "", "", "", "", "", "", "", "", "",
      "OPTIMIZATION",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "PURGE",
      "", "", "", "",
      "LOOP",
      "INFILE",
      "",
      "ALL",
      "",
      "NCHAR",
      "", "", "", "", "",
      "NUMBER",
      "",
      "FULLTEXT",
      "", "", "",
      "VARCHAR2",
      "", "", "", "",
      "BREAK",
      "", "", "", "", "", "", "",
      "DAY_MINUTE",
      "", "",
      "MLSLABEL",
      "", "", "",
      "LEAVE",
      "", "",
      "DUMP",
      "OPTIMIZER_COSTS",
      "", "", "", "",
      "SOUNDEX",
      "VALIDATE",
      "", "", "", "",
      "ARRAY_EXISTS",
      "",
      "PRECISION",
      "AFTER",
      "", "", "", "", "", "", "", "",
      "INCREMENT",
      "", "",
      "SQLEXCEPTION",
      "", "",
      "UPD",
      "", "", "", "", "", "", "", "", "",
      "",
      "VARCHAR",
      "EXECUTE",
      "",
      "TYPE",
      "",
      "EXCEPT",
      "", "",
      "INDEX",
      "", "", "",
      "LONGTEXT",
      "", "", "",
      "NULLIF",
      "", "", "",
      "OVER",
      "", "", "",
      "IDENTIFIED",
      "SCHEMA",
      "", "", "", "", "", "", "", "",
      "ADMIN",
      "", "", "", "", "", "", "", "", "",
      "CHARACTERS",
      "",
      "MAX",
      "",
      "IO_AFTER_GTIDS",
      "",
      "BEGIN_PARTITION",
      "", "",
      "PERMANENT",
      "", "", "", "", "", "", "", "",
      "END-EXEC",
      "",
      "LOCALTIMESTAMP",
      "", "", "", "",
      "UTC_DATE",
      "", "", "", "", "", "",
      "EXTRACT",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "GENERAL",
      "EXTERNAL",
      "", "", "",
      "TSEQUAL",
      "",
      "CHARACTER",
      "", "", "", "", "", "", "", "", "",
      "",
      "RIGHT",
      "",
      "LEVEL",
      "", "", "", "", "",
      "UPDATE",
      "PROC",
      "", "", "", "", "", "",
      "RIGHTS",
      "", "", "", "", "",
      "VOLATILE",
      "",
      "PIECESIZE",
      "DEPTH",
      "", "", "", "", "", "", "", "", "",
      "",
      "SUBMULTISET",
      "", "", "", "", "", "",
      "JSON_SCALAR",
      "",
      "ROUND_HALF_EVEN",
      "", "",
      "OF",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "DAY_SECOND",
      "", "", "", "", "", "", "", "",
      "OBID",
      "", "",
      "OFFSET",
      "LISTAGG",
      "", "",
      "VIRTUAL",
      "", "",
      "UNPIVOT",
      "HASHBUCKET",
      "", "", "", "",
      "MINDEX",
      "",
      "ENABLED",
      "OFFSETS",
      "", "", "",
      "PREPARE",
      "", "",
      "ROUND_HALF_DOWN",
      "", "", "", "", "", "", "", "", "",
      "DATABLOCKSIZE",
      "",
      "BEGIN_FRAME",
      "",
      "NTH_VALUE",
      "LABEL",
      "",
      "LAST_VALUE",
      "",
      "DBCC",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "VARIADIC",
      "",
      "JOURNAL",
      "", "",
      "PARTIAL",
      "GROUPING",
      "",
      "OVERRIDE",
      "", "", "", "", "", "", "", "", "",
      "FETCH",
      "", "", "", "",
      "GROUP",
      "", "", "", "", "", "", "", "",
      "EXCEPTION",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "ROWGUIDCOL",
      "",
      "LIKE",
      "", "", "", "", "", "", "",
      "SPECIFIC",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "UESCAPE",
      "FIELDPROC",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "FASTEXPORT",
      "",
      "DYNAMIC",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "HOLDLOCK",
      "", "", "", "", "",
      "SYSTEM_USER",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "MAVG",
      "", "", "",
      "ACCESSIBLE",
      "", "", "", "",
      "TIMESTAMP",
      "", "", "", "", "", "", "", "", "",
      "ISOBID",
      "", "", "", "", "",
      "EQUALS",
      "", "",
      "ROW_NUMBER",
      "", "", "", "",
      "EXEC",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "XMLEXISTS",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "PERCENTILE_CONT",
      "",
      "STDDEV_POP",
      "", "", "", "", "", "", "", "",
      "MCHARACTERS",
      "",
      "WLM",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "VARCHARACTER",
      "", "", "", "", "", "",
      "OFFLINE",
      "", "", "", "", "", "",
      "PERCENTILE_DISC",
      "", "", "", "",
      "YEAR_MONTH",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "WHEN",
      "", "", "", "", "", "", "", "", "",
      "LOGGING",
      "SUBSTRING",
      "", "",
      "REGR_SXX",
      "", "", "", "", "", "", "", "",
      "SYSTEM_TIME",
      "ABS",
      "", "",
      "ABSENT",
      "",
      "PROFILE",
      "", "",
      "ROLLBACK",
      "", "",
      "OPENXML",
      "WHERE",
      "", "", "", "", "",
      "SCRATCHPAD",
      "", "", "", "", "", "",
      "ELSEIF",
      "", "", "", "",
      "PCTFREE",
      "", "", "",
      "TABLESAMPLE",
      "", "",
      "EXCLUSIVE",
      "",
      "ATOMIC",
      "", "", "", "", "",
      "JSON_EXISTS",
      "",
      "AVE",
      "", "",
      "XMLCAST",
      "", "", "", "", "", "", "", "", "",
      "IF",
      "", "", "", "", "", "",
      "ABORT",
      "ROWNUM",
      "SYSTEM",
      "", "", "", "", "", "",
      "STDDEV_SAMP",
      "",
      "TRIM_ARRAY",
      "", "", "", "", "", "",
      "ABSOLUTE",
      "", "", "", "", "", "", "",
      "CHECKPOINT",
      "", "", "", "", "", "",
      "TINYTEXT",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "ECHO",
      "", "",
      "MAXIMUM",
      "",
      "IMMEDIATE",
      "",
      "ABORTSESSION",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "LONGBLOB",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "VERBOSE",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "FIRST_VALUE",
      "",
      "CV",
      "",
      "IDENTITY",
      "", "", "", "",
      "JSON_TABLE_PRIMITIVE",
      "", "",
      "NEW",
      "", "", "", "", "", "", "", "", "",
      "ROW",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "DENY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "DESTROY",
      "", "", "",
      "WITHIN",
      "SQLTEXT",
      "", "", "", "", "", "", "",
      "PERM",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "STRAIGHT_JOIN",
      "",
      "ORDINALITY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "OLD_TABLE",
      "", "", "", "", "", "", "", "", "",
      "OPENROWSET",
      "TABLESPACE",
      "WITHOUT",
      "UPPER",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "MAXVALUE",
      "DAY_MICROSECOND",
      "", "", "", "", "", "", "", "", "",
      "",
      "INHERIT",
      "", "", "",
      "VARBYTE",
      "", "", "",
      "INTERVAL",
      "", "", "", "", "", "", "", "",
      "HAVING",
      "", "", "", "", "", "", "",
      "ASENSITIVE",
      "", "", "",
      "RAW",
      "",
      "PROPORTIONAL",
      "", "", "", "",
      "PARTITIONING",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "UTC_TIME",
      "DIV",
      "", "", "", "", "",
      "DAY",
      "CLOB",
      "",
      "JSON_ARRAYAGG",
      "", "", "", "", "", "",
      "JSON_OBJECT",
      "STAY",
      "", "", "", "", "", "", "", "", "",
      "POWER",
      "ARRAY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "SQL_BIG_RESULT",
      "", "", "", "", "", "", "", "", "",
      "AGGREGATE",
      "", "", "", "", "", "", "", "", "",
      "",
      "LOCKSIZE",
      "", "", "",
      "PRESERVE",
      "", "",
      "REGR_SXY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "SQL_CALC_FOUND_ROWS",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "OVERLAPS",
      "",
      "VALUE_OF",
      "",
      "ATANH",
      "", "", "", "", "", "",
      "SHUTDOWN",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "ARRAY_AGG",
      "", "",
      "EXPLAIN",
      "", "", "",
      "BUFFERPOOL",
      "", "", "", "", "", "", "", "", "",
      "",
      "KEY",
      "",
      "WHILE",
      "", "", "", "", "",
      "MODIFY",
      "", "",
      "ROUND_HALF_UP",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "UNIQUE",
      "PTF",
      "ASINH",
      "",
      "PIVOT",
      "", "",
      "OFF",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "GIVE",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "PRIVATE",
      "", "", "", "", "", "",
      "OBJECT",
      "BY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "OBJECTS",
      "", "", "", "",
      "ILIKE",
      "", "", "", "", "", "", "",
      "SUBSTRING_REGEX",
      "", "",
      "SEEK",
      "", "", "", "", "",
      "COSH",
      "", "", "", "", "", "", "", "", "",
      "JSON_VALUE",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "SQL_SMALL_RESULT",
      "", "", "", "", "",
      "NEW_TABLE",
      "AVERAGE",
      "", "", "",
      "NO_WRITE_TO_BINLOG",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "ACOSH",
      "", "", "",
      "ALLOW",
      "", "", "", "", "", "", "",
      "SKIP",
      "",
      "BLOB",
      "",
      "FALLBACK",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "PLACING",
      "", "", "", "",
      "TINYBLOB",
      "", "", "", "", "",
      "EXP",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "OCCURRENCES_REGEX",
      "", "", "", "",
      "COVAR_SAMP",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "UPPERCASE",
      "", "", "",
      "SEARCH",
      "UPDATETEXT",
      "", "",
      "SEMANTICKEYPHRASETABLE",
      "", "", "",
      "THRESHOLD",
      "", "",
      "WIDTH_BUCKET",
      "",
      "TANH",
      "", "", "",
      "RANK",
      "", "", "", "", "", "", "", "",
      "CONCURRENTLY",
      "",
      "SINH",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "ADD_MONTHS",
      "", "", "", "", "", "",
      "JSON_ARRAY",
      "REGR_SYY",
      "", "", "", "",
      "AUTHORIZATION",
      "", "", "",
      "VARIABLE",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "DISK",
      "", "", "", "", "", "", "", "", "",
      "GRAPHIC",
      "", "", "", "", "",
      "AMP",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "VAR_POP",
      "", "", "", "",
      "PRIVILEGES",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "AUX",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "SYMMETRIC",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "VAR_SAMP",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "HASH",
      "", "", "", "", "", "", "", "",
      "PROGRAM",
      "BOTH",
      "", "", "", "",
      "VALIDPROC",
      "", "", "", "", "", "",
      "OPTIONALLY",
      "", "", "", "", "", "", "", "",
      "VARGRAPHIC",
      "", "", "",
      "ANY_VALUE",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "BINARY",
      "",
      "SYSTIMESTAMP",
      "", "", "",
      "LIKE_REGEX",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "MEDIUMBLOB",
      "",
      "CHECK",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "EMPTY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "CHAR2HEXINT",
      "", "", "", "", "", "", "",
      "COPY",
      "LOCKING",
      "JSON_OBJECTAGG",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "EVERY",
      "",
      "PREVVAL",
      "", "", "", "", "",
      "IO_BEFORE_GTIDS",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "AVG",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "BREADTH",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "GLOBAL",
      "", "", "", "", "", "", "",
      "XMLNAMESPACES",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "SQLWARNING",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "CHARACTER_LENGTH",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "ONLY",
      "",
      "POSTFIX",
      "EQ",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "TRANSLATE_CHK",
      "", "", "", "", "", "", "", "",
      "LC_CTYPE",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "BULK",
      "", "",
      "PUBLIC",
      "", "", "", "", "", "", "",
      "POSITION_REGEX",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "BACKUP",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "ASYMMETRIC",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "VARYING",
      "", "", "", "", "", "", "", "", "",
      "",
      "REFRESH",
      "", "", "", "", "", "", "", "", "",
      "",
      "ACCESS_LOCK",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "HASHAMP",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "WHENEVER",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "WINDOW",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "CURRENT_PATH",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "PACKAGE",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "SYNONYM",
      "", "", "", "", "", "", "", "", "",
      "COVAR_POP",
      "", "", "", "",
      "QUALIFY",
      "", "", "",
      "CHAR_LENGTH",
      "ANY",
      "", "", "", "", "", "", "",
      "REGR_AVGX",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "LOCK",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "SUMMARY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "WORK",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "UTC_TIMESTAMP",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "OPENQUERY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "SHOW",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "SKEW",
      "",
      "VIEW",
      "", "", "", "", "", "", "",
      "WITH",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "",
      "UNKNOWN",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "EACH",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "TEMPORARY",
      "PREFIX",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "FRAME_ROW",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "INITIALLY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "JSON_QUERY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "",
      "SECQTY",
      "", "",
      "HIGH_PRIORITY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "WITHIN_GROUP",
      "",
      "HASHROW",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "PATH",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "LOCKMAX",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "UNLOCK",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "",
      "OCTET_LENGTH",
      "", "", "", "", "", "", "",
      "REGR_AVGY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "",
      "HASHBAKAMP",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "OVERLAY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "ARRAY_MAX_CARDINALITY",
      "", "", "", "", "", "", "", "", "",
      "PERCENT_RANK",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "PRIMARY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "NOCHECK",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "",
      "LOW_PRIORITY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "AUXILIARY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "",
      "VARBINARY",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "",
      "PRIQTY"
    };

  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register unsigned int key = hash (str, len);

      if (key <= MAX_HASH_VALUE)
        {
          register const char *s = wordlist[key];

          if ((((unsigned char)*str ^ (unsigned char)*s) & ~32) == 0 && !gperf_case_strncmp (str, s, len) && s[len] == '\0')
            return s;
        }
    }
  return 0;
}
