blank_issues_enabled: true
contact_links:
  - name: Got an idea?
    url: https://github.com/Mozilla-Ocho/llamafile/discussions/categories/ideas
    about: Pop it there. It may then become an enhancement ticket.
  - name: Got a question?
    url: https://github.com/Mozilla-Ocho/llamafile/discussions/categories/q-a
    about: Ask a question there!
  - name: Is your problem more about the underlying llama.cpp engine?
    url: https://github.com/ggerganov/llama.cpp/issues/new/choose
    about: Head to the llama.cpp reporting page instead


