# -*- coding: utf-8 -*-
double_conversion_sources = [
    'bignum.cc',
    'bignum-dtoa.cc',
    'cached-powers.cc',
    'double-to-string.cc',
    'fast-dtoa.cc',
    'fixed-dtoa.cc',
    'string-to-double.cc',
    'strtod.cc'
  ]
Return('double_conversion_sources')
